// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: order_status_history.sql

package repository_order_status_history

import (
	"context"

	"github.com/google/uuid"
	"github.com/stickpro/go-store/internal/models"
)

const listByOrderID = `-- name: ListByOrderID :many
SELECT id, order_id, from_status, to_status, actor, comment, created_at FROM order_status_history
WHERE order_id = $1
ORDER BY created_at
`

func (q *Queries) ListByOrderID(ctx context.Context, orderID uuid.UUID) ([]*models.OrderStatusHistory, error) {
	rows, err := q.db.Query(ctx, listByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*models.OrderStatusHistory{}
	for rows.Next() {
		var i models.OrderStatusHistory
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.FromStatus,
			&i.ToStatus,
			&i.Actor,
			&i.Comment,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
