// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: order_status_history_gen.sql

package repository_order_status_history

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/stickpro/go-store/internal/models"
)

const create = `-- name: Create :one
INSERT INTO order_status_history (order_id, from_status, to_status, actor, comment)
	VALUES ($1, $2, $3, $4, $5)
	RETURNING id, order_id, from_status, to_status, actor, comment, created_at
`

type CreateParams struct {
	OrderID    uuid.UUID   `db:"order_id" json:"order_id"`
	FromStatus pgtype.Text `db:"from_status" json:"from_status"`
	ToStatus   string      `db:"to_status" json:"to_status"`
	Actor      string      `db:"actor" json:"actor"`
	Comment    pgtype.Text `db:"comment" json:"comment"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (*models.OrderStatusHistory, error) {
	row := q.db.QueryRow(ctx, create,
		arg.OrderID,
		arg.FromStatus,
		arg.ToStatus,
		arg.Actor,
		arg.Comment,
	)
	var i models.OrderStatusHistory
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.FromStatus,
		&i.ToStatus,
		&i.Actor,
		&i.Comment,
		&i.CreatedAt,
	)
	return &i, err
}
