// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: order_items.sql

package repository_order_items

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
	"github.com/stickpro/go-store/internal/models"
)

const deleteByID = `-- name: DeleteByID :exec
DELETE FROM order_items WHERE id = $1
`

func (q *Queries) DeleteByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteByID, id)
	return err
}

const listByOrderID = `-- name: ListByOrderID :many
SELECT id, order_id, product_id, variant_id, sku, name, slug, image_path, unit_price, quantity, line_total, weight_kg, length_cm, width_cm, height_cm FROM order_items WHERE order_id = $1 ORDER BY id
`

func (q *Queries) ListByOrderID(ctx context.Context, orderID uuid.UUID) ([]*models.OrderItem, error) {
	rows, err := q.db.Query(ctx, listByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*models.OrderItem{}
	for rows.Next() {
		var i models.OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.VariantID,
			&i.Sku,
			&i.Name,
			&i.Slug,
			&i.ImagePath,
			&i.UnitPrice,
			&i.Quantity,
			&i.LineTotal,
			&i.WeightKg,
			&i.LengthCm,
			&i.WidthCm,
			&i.HeightCm,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listByOrderIDs = `-- name: ListByOrderIDs :many
SELECT id, order_id, product_id, variant_id, sku, name, slug, image_path, unit_price, quantity, line_total, weight_kg, length_cm, width_cm, height_cm FROM order_items
WHERE order_id = ANY ($1::uuid[])
ORDER BY order_id, id
`

func (q *Queries) ListByOrderIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]*models.OrderItem, error) {
	rows, err := q.db.Query(ctx, listByOrderIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*models.OrderItem{}
	for rows.Next() {
		var i models.OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.VariantID,
			&i.Sku,
			&i.Name,
			&i.Slug,
			&i.ImagePath,
			&i.UnitPrice,
			&i.Quantity,
			&i.LineTotal,
			&i.WeightKg,
			&i.LengthCm,
			&i.WidthCm,
			&i.HeightCm,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateQuantity = `-- name: UpdateQuantity :one
UPDATE order_items
SET quantity   = $2,
    line_total = $3
WHERE id = $1
RETURNING id, order_id, product_id, variant_id, sku, name, slug, image_path, unit_price, quantity, line_total, weight_kg, length_cm, width_cm, height_cm
`

type UpdateQuantityParams struct {
	ID        uuid.UUID       `db:"id" json:"id"`
	Quantity  int64           `db:"quantity" json:"quantity"`
	LineTotal decimal.Decimal `db:"line_total" json:"line_total"`
}

func (q *Queries) UpdateQuantity(ctx context.Context, arg UpdateQuantityParams) (*models.OrderItem, error) {
	row := q.db.QueryRow(ctx, updateQuantity, arg.ID, arg.Quantity, arg.LineTotal)
	var i models.OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.VariantID,
		&i.Sku,
		&i.Name,
		&i.Slug,
		&i.ImagePath,
		&i.UnitPrice,
		&i.Quantity,
		&i.LineTotal,
		&i.WeightKg,
		&i.LengthCm,
		&i.WidthCm,
		&i.HeightCm,
	)
	return &i, err
}
