// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: order_items_gen.sql

package repository_order_items

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
	"github.com/stickpro/go-store/internal/models"
)

const create = `-- name: Create :one
INSERT INTO order_items (order_id, product_id, variant_id, sku, name, slug, image_path, unit_price, quantity, line_total, weight_kg, length_cm, width_cm, height_cm)
	VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
	RETURNING id, order_id, product_id, variant_id, sku, name, slug, image_path, unit_price, quantity, line_total, weight_kg, length_cm, width_cm, height_cm
`

type CreateParams struct {
	OrderID   uuid.UUID       `db:"order_id" json:"order_id"`
	ProductID uuid.NullUUID   `db:"product_id" json:"product_id"`
	VariantID uuid.NullUUID   `db:"variant_id" json:"variant_id"`
	Sku       pgtype.Text     `db:"sku" json:"sku"`
	Name      string          `db:"name" json:"name"`
	Slug      pgtype.Text     `db:"slug" json:"slug"`
	ImagePath pgtype.Text     `db:"image_path" json:"image_path"`
	UnitPrice decimal.Decimal `db:"unit_price" json:"unit_price"`
	Quantity  int64           `db:"quantity" json:"quantity"`
	LineTotal decimal.Decimal `db:"line_total" json:"line_total"`
	WeightKg  decimal.Decimal `db:"weight_kg" json:"weight_kg"`
	LengthCm  decimal.Decimal `db:"length_cm" json:"length_cm"`
	WidthCm   decimal.Decimal `db:"width_cm" json:"width_cm"`
	HeightCm  decimal.Decimal `db:"height_cm" json:"height_cm"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (*models.OrderItem, error) {
	row := q.db.QueryRow(ctx, create,
		arg.OrderID,
		arg.ProductID,
		arg.VariantID,
		arg.Sku,
		arg.Name,
		arg.Slug,
		arg.ImagePath,
		arg.UnitPrice,
		arg.Quantity,
		arg.LineTotal,
		arg.WeightKg,
		arg.LengthCm,
		arg.WidthCm,
		arg.HeightCm,
	)
	var i models.OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.VariantID,
		&i.Sku,
		&i.Name,
		&i.Slug,
		&i.ImagePath,
		&i.UnitPrice,
		&i.Quantity,
		&i.LineTotal,
		&i.WeightKg,
		&i.LengthCm,
		&i.WidthCm,
		&i.HeightCm,
	)
	return &i, err
}
