// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository_order_items

import (
	"context"

	"github.com/google/uuid"
	"github.com/stickpro/go-store/internal/models"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) (*models.OrderItem, error)
	// Most recent paid-or-later order by this user that contains the given variant.
	// Drives the "verified purchase" gate on product reviews; returns no row when
	// the user has not bought the variant.
	GetVerifiedPurchaseOrderID(ctx context.Context, arg GetVerifiedPurchaseOrderIDParams) (uuid.UUID, error)
	ListByOrderID(ctx context.Context, orderID uuid.UUID) ([]*models.OrderItem, error)
	ListByOrderIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]*models.OrderItem, error)
}

var _ Querier = (*Queries)(nil)
