// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository_order_items

import (
	"context"

	"github.com/google/uuid"
	"github.com/stickpro/go-store/internal/models"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) (*models.OrderItem, error)
	ListByOrderID(ctx context.Context, orderID uuid.UUID) ([]*models.OrderItem, error)
	ListByOrderIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]*models.OrderItem, error)
}

var _ Querier = (*Queries)(nil)
