// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository_users

import (
	"context"

	"github.com/google/uuid"
	"github.com/stickpro/go-store/internal/models"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) (*models.User, error)
	Delete(ctx context.Context, id uuid.UUID) error
	GetAll(ctx context.Context, arg GetAllParams) ([]*models.User, error)
	GetByEmail(ctx context.Context, email string) (*models.User, error)
	GetByID(ctx context.Context, id uuid.UUID) (*models.User, error)
	Update(ctx context.Context, arg UpdateParams) (*models.User, error)
}

var _ Querier = (*Queries)(nil)
