// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository_users

import (
	"context"

	"github.com/google/uuid"
	"github.com/stickpro/go-store/internal/models"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) (*models.User, error)
	// Customer counters for the admin dashboard. Admin accounts and soft-deleted
	// users are excluded; new_today uses the store-timezone day boundary params.
	DashboardCustomerStats(ctx context.Context, arg DashboardCustomerStatsParams) (*DashboardCustomerStatsRow, error)
	Delete(ctx context.Context, id uuid.UUID) error
	GetAll(ctx context.Context, arg GetAllParams) ([]*models.User, error)
	GetByEmail(ctx context.Context, email string) (*models.User, error)
	GetByID(ctx context.Context, id uuid.UUID) (*models.User, error)
	MarkEmailVerified(ctx context.Context, id uuid.UUID) error
	SetPassword(ctx context.Context, arg SetPasswordParams) error
	Update(ctx context.Context, arg UpdateParams) (*models.User, error)
}

var _ Querier = (*Queries)(nil)
