// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package repository_users

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/stickpro/go-store/internal/models"
)

const dashboardCustomerStats = `-- name: DashboardCustomerStats :one
SELECT
    count(*) FILTER (WHERE created_at >= $1
                       AND created_at < $2) AS new_today,
    count(*)                                                  AS total
FROM users
WHERE deleted_at IS NULL
  AND is_admin IS NOT TRUE
`

type DashboardCustomerStatsParams struct {
	TodayFrom pgtype.Timestamp `db:"today_from" json:"today_from"`
	TodayTo   pgtype.Timestamp `db:"today_to" json:"today_to"`
}

type DashboardCustomerStatsRow struct {
	NewToday int64 `db:"new_today" json:"new_today"`
	Total    int64 `db:"total" json:"total"`
}

// Customer counters for the admin dashboard. Admin accounts and soft-deleted
// users are excluded; new_today uses the store-timezone day boundary params.
func (q *Queries) DashboardCustomerStats(ctx context.Context, arg DashboardCustomerStatsParams) (*DashboardCustomerStatsRow, error) {
	row := q.db.QueryRow(ctx, dashboardCustomerStats, arg.TodayFrom, arg.TodayTo)
	var i DashboardCustomerStatsRow
	err := row.Scan(&i.NewToday, &i.Total)
	return &i, err
}

const getByEmail = `-- name: GetByEmail :one
SELECT id, email, email_verified_at, password, remember_token, location, language, created_at, updated_at, deleted_at, is_admin, banned
FROM users
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetByEmail(ctx context.Context, email string) (*models.User, error) {
	row := q.db.QueryRow(ctx, getByEmail, email)
	var i models.User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.Password,
		&i.RememberToken,
		&i.Location,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IsAdmin,
		&i.Banned,
	)
	return &i, err
}

const getByID = `-- name: GetByID :one
SELECT id, email, email_verified_at, password, remember_token, location, language, created_at, updated_at, deleted_at, is_admin, banned
FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetByID(ctx context.Context, id uuid.UUID) (*models.User, error) {
	row := q.db.QueryRow(ctx, getByID, id)
	var i models.User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.Password,
		&i.RememberToken,
		&i.Location,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IsAdmin,
		&i.Banned,
	)
	return &i, err
}

const markEmailVerified = `-- name: MarkEmailVerified :exec
UPDATE users
SET email_verified_at = now(),
    updated_at        = now()
WHERE id = $1
`

func (q *Queries) MarkEmailVerified(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markEmailVerified, id)
	return err
}

const setPassword = `-- name: SetPassword :exec
UPDATE users
SET password   = $2,
    updated_at = now()
WHERE email = $1
`

type SetPasswordParams struct {
	Email    string      `db:"email" json:"email" validate:"required,email"`
	Password pgtype.Text `db:"password" json:"password"`
}

func (q *Queries) SetPassword(ctx context.Context, arg SetPasswordParams) error {
	_, err := q.db.Exec(ctx, setPassword, arg.Email, arg.Password)
	return err
}
