// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media.sql

package repository_media

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/stickpro/go-store/internal/models"
)

const createWithSourceURL = `-- name: CreateWithSourceURL :one
INSERT INTO media (name, path, file_name, mime_type, disk_type, size, source_url, width, height, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, now())
RETURNING id, name, path, file_name, mime_type, disk_type, size, created_at, source_url, width, height
`

type CreateWithSourceURLParams struct {
	Name      string      `db:"name" json:"name"`
	Path      string      `db:"path" json:"path"`
	FileName  string      `db:"file_name" json:"file_name"`
	MimeType  string      `db:"mime_type" json:"mime_type"`
	DiskType  string      `db:"disk_type" json:"disk_type"`
	Size      int64       `db:"size" json:"size"`
	SourceUrl pgtype.Text `db:"source_url" json:"source_url"`
	Width     int32       `db:"width" json:"width"`
	Height    int32       `db:"height" json:"height"`
}

func (q *Queries) CreateWithSourceURL(ctx context.Context, arg CreateWithSourceURLParams) (*models.Medium, error) {
	row := q.db.QueryRow(ctx, createWithSourceURL,
		arg.Name,
		arg.Path,
		arg.FileName,
		arg.MimeType,
		arg.DiskType,
		arg.Size,
		arg.SourceUrl,
		arg.Width,
		arg.Height,
	)
	var i models.Medium
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.FileName,
		&i.MimeType,
		&i.DiskType,
		&i.Size,
		&i.CreatedAt,
		&i.SourceUrl,
		&i.Width,
		&i.Height,
	)
	return &i, err
}

const get = `-- name: Get :one
SELECT id, name, path, file_name, mime_type, disk_type, size, created_at, source_url, width, height FROM media WHERE id = $1 LIMIT 1
`

func (q *Queries) Get(ctx context.Context, id uuid.UUID) (*models.Medium, error) {
	row := q.db.QueryRow(ctx, get, id)
	var i models.Medium
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.FileName,
		&i.MimeType,
		&i.DiskType,
		&i.Size,
		&i.CreatedAt,
		&i.SourceUrl,
		&i.Width,
		&i.Height,
	)
	return &i, err
}

const getBySourceURL = `-- name: GetBySourceURL :one
SELECT id, name, path, file_name, mime_type, disk_type, size, created_at, source_url, width, height FROM media WHERE source_url = $1 LIMIT 1
`

func (q *Queries) GetBySourceURL(ctx context.Context, sourceUrl pgtype.Text) (*models.Medium, error) {
	row := q.db.QueryRow(ctx, getBySourceURL, sourceUrl)
	var i models.Medium
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.FileName,
		&i.MimeType,
		&i.DiskType,
		&i.Size,
		&i.CreatedAt,
		&i.SourceUrl,
		&i.Width,
		&i.Height,
	)
	return &i, err
}
