// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: media.sql

package repository_media

import (
	"context"

	"github.com/google/uuid"
	"github.com/stickpro/go-store/internal/models"
)

const get = `-- name: Get :one
SELECT id, name, path, file_name, mime_type, disk_type, size, created_at FROM media WHERE id = $1 LIMIT 1
`

func (q *Queries) Get(ctx context.Context, id uuid.UUID) (*models.Medium, error) {
	row := q.db.QueryRow(ctx, get, id)
	var i models.Medium
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.FileName,
		&i.MimeType,
		&i.DiskType,
		&i.Size,
		&i.CreatedAt,
	)
	return &i, err
}
