// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package repository_orders

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
	"github.com/stickpro/go-store/internal/models"
)

const countAdmin = `-- name: CountAdmin :one
SELECT count(*) FROM orders
WHERE ($1::varchar IS NULL OR status = $1)
  AND ($2::varchar IS NULL OR payment_status = $2)
  AND ($3::varchar IS NULL OR source = $3)
  AND ($4::uuid IS NULL OR user_id = $4)
  AND ($5::timestamp IS NULL OR created_at >= $5)
  AND ($6::timestamp IS NULL OR created_at <= $6)
`

type CountAdminParams struct {
	Status        pgtype.Text      `db:"status" json:"status"`
	PaymentStatus pgtype.Text      `db:"payment_status" json:"payment_status"`
	Source        pgtype.Text      `db:"source" json:"source"`
	UserID        uuid.NullUUID    `db:"user_id" json:"user_id"`
	CreatedFrom   pgtype.Timestamp `db:"created_from" json:"created_from"`
	CreatedTo     pgtype.Timestamp `db:"created_to" json:"created_to"`
}

func (q *Queries) CountAdmin(ctx context.Context, arg CountAdminParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAdmin,
		arg.Status,
		arg.PaymentStatus,
		arg.Source,
		arg.UserID,
		arg.CreatedFrom,
		arg.CreatedTo,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countByUser = `-- name: CountByUser :one
SELECT count(*) FROM orders WHERE user_id = $1
`

func (q *Queries) CountByUser(ctx context.Context, userID uuid.NullUUID) (int64, error) {
	row := q.db.QueryRow(ctx, countByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const dashboardOrderStats = `-- name: DashboardOrderStats :one
SELECT
    count(*)                                                                        AS total,
    count(*) FILTER (WHERE created_at >= $1
                       AND created_at < $2)                       AS today,

    count(*) FILTER (WHERE status = 'pending')                                      AS status_pending,
    count(*) FILTER (WHERE status = 'paid')                                         AS status_paid,
    count(*) FILTER (WHERE status = 'processing')                                   AS status_processing,
    count(*) FILTER (WHERE status = 'shipped')                                      AS status_shipped,
    count(*) FILTER (WHERE status = 'delivered')                                    AS status_delivered,
    count(*) FILTER (WHERE status = 'cancelled')                                    AS status_cancelled,
    count(*) FILTER (WHERE status = 'refunded')                                     AS status_refunded,

    count(*) FILTER (WHERE payment_status = 'unpaid')                               AS payment_unpaid,
    count(*) FILTER (WHERE payment_status = 'paid')                                 AS payment_paid,
    count(*) FILTER (WHERE payment_status = 'refunded')                             AS payment_refunded,
    count(*) FILTER (WHERE payment_status = 'failed')                               AS payment_failed,

    coalesce(sum(grand_total) FILTER (WHERE payment_status = 'paid'
                                        AND created_at >= $1
                                        AND created_at < $2), 0)::numeric  AS revenue_today,
    coalesce(sum(grand_total) FILTER (WHERE payment_status = 'paid'
                                        AND created_at >= $3
                                        AND created_at < $4), 0)::numeric AS revenue_period,
    count(*) FILTER (WHERE payment_status = 'paid'
                       AND created_at >= $3
                       AND created_at < $4)                      AS paid_orders_period
FROM orders
`

type DashboardOrderStatsParams struct {
	TodayFrom  pgtype.Timestamp `db:"today_from" json:"today_from"`
	TodayTo    pgtype.Timestamp `db:"today_to" json:"today_to"`
	PeriodFrom pgtype.Timestamp `db:"period_from" json:"period_from"`
	PeriodTo   pgtype.Timestamp `db:"period_to" json:"period_to"`
}

type DashboardOrderStatsRow struct {
	Total            int64           `db:"total" json:"total"`
	Today            int64           `db:"today" json:"today"`
	StatusPending    int64           `db:"status_pending" json:"status_pending"`
	StatusPaid       int64           `db:"status_paid" json:"status_paid"`
	StatusProcessing int64           `db:"status_processing" json:"status_processing"`
	StatusShipped    int64           `db:"status_shipped" json:"status_shipped"`
	StatusDelivered  int64           `db:"status_delivered" json:"status_delivered"`
	StatusCancelled  int64           `db:"status_cancelled" json:"status_cancelled"`
	StatusRefunded   int64           `db:"status_refunded" json:"status_refunded"`
	PaymentUnpaid    int64           `db:"payment_unpaid" json:"payment_unpaid"`
	PaymentPaid      int64           `db:"payment_paid" json:"payment_paid"`
	PaymentRefunded  int64           `db:"payment_refunded" json:"payment_refunded"`
	PaymentFailed    int64           `db:"payment_failed" json:"payment_failed"`
	RevenueToday     decimal.Decimal `db:"revenue_today" json:"revenue_today"`
	RevenuePeriod    decimal.Decimal `db:"revenue_period" json:"revenue_period"`
	PaidOrdersPeriod int64           `db:"paid_orders_period" json:"paid_orders_period"`
}

// One-shot order snapshot for the admin dashboard. Status / payment buckets and
// `total` are all-time (current distribution); `today` and `revenue_today` use
// the day-boundary params; `revenue_period` / `paid_orders_period` use the
// selected range. Revenue sums grand_total of payment_status = 'paid' orders only.
func (q *Queries) DashboardOrderStats(ctx context.Context, arg DashboardOrderStatsParams) (*DashboardOrderStatsRow, error) {
	row := q.db.QueryRow(ctx, dashboardOrderStats,
		arg.TodayFrom,
		arg.TodayTo,
		arg.PeriodFrom,
		arg.PeriodTo,
	)
	var i DashboardOrderStatsRow
	err := row.Scan(
		&i.Total,
		&i.Today,
		&i.StatusPending,
		&i.StatusPaid,
		&i.StatusProcessing,
		&i.StatusShipped,
		&i.StatusDelivered,
		&i.StatusCancelled,
		&i.StatusRefunded,
		&i.PaymentUnpaid,
		&i.PaymentPaid,
		&i.PaymentRefunded,
		&i.PaymentFailed,
		&i.RevenueToday,
		&i.RevenuePeriod,
		&i.PaidOrdersPeriod,
	)
	return &i, err
}

const getByIdempotencyKey = `-- name: GetByIdempotencyKey :one
SELECT id, order_number, user_id, status, payment_status, payment_method, currency, email, phone, ship_city_id, ship_city_name, ship_address, ship_postcode, ship_recipient, shipping_method, subtotal, discount_total, shipping_total, tax_total, grand_total, comment, idempotency_key, created_at, updated_at, paid_at, cancelled_at, ship_provider, ship_tariff_code, ship_point_code, ship_min_days, ship_max_days, source FROM orders WHERE idempotency_key = $1 LIMIT 1
`

func (q *Queries) GetByIdempotencyKey(ctx context.Context, idempotencyKey pgtype.Text) (*models.Order, error) {
	row := q.db.QueryRow(ctx, getByIdempotencyKey, idempotencyKey)
	var i models.Order
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.UserID,
		&i.Status,
		&i.PaymentStatus,
		&i.PaymentMethod,
		&i.Currency,
		&i.Email,
		&i.Phone,
		&i.ShipCityID,
		&i.ShipCityName,
		&i.ShipAddress,
		&i.ShipPostcode,
		&i.ShipRecipient,
		&i.ShippingMethod,
		&i.Subtotal,
		&i.DiscountTotal,
		&i.ShippingTotal,
		&i.TaxTotal,
		&i.GrandTotal,
		&i.Comment,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaidAt,
		&i.CancelledAt,
		&i.ShipProvider,
		&i.ShipTariffCode,
		&i.ShipPointCode,
		&i.ShipMinDays,
		&i.ShipMaxDays,
		&i.Source,
	)
	return &i, err
}

const getByNumber = `-- name: GetByNumber :one
SELECT id, order_number, user_id, status, payment_status, payment_method, currency, email, phone, ship_city_id, ship_city_name, ship_address, ship_postcode, ship_recipient, shipping_method, subtotal, discount_total, shipping_total, tax_total, grand_total, comment, idempotency_key, created_at, updated_at, paid_at, cancelled_at, ship_provider, ship_tariff_code, ship_point_code, ship_min_days, ship_max_days, source FROM orders WHERE order_number = $1 LIMIT 1
`

func (q *Queries) GetByNumber(ctx context.Context, orderNumber int64) (*models.Order, error) {
	row := q.db.QueryRow(ctx, getByNumber, orderNumber)
	var i models.Order
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.UserID,
		&i.Status,
		&i.PaymentStatus,
		&i.PaymentMethod,
		&i.Currency,
		&i.Email,
		&i.Phone,
		&i.ShipCityID,
		&i.ShipCityName,
		&i.ShipAddress,
		&i.ShipPostcode,
		&i.ShipRecipient,
		&i.ShippingMethod,
		&i.Subtotal,
		&i.DiscountTotal,
		&i.ShippingTotal,
		&i.TaxTotal,
		&i.GrandTotal,
		&i.Comment,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaidAt,
		&i.CancelledAt,
		&i.ShipProvider,
		&i.ShipTariffCode,
		&i.ShipPointCode,
		&i.ShipMinDays,
		&i.ShipMaxDays,
		&i.Source,
	)
	return &i, err
}

const getByNumberForUpdate = `-- name: GetByNumberForUpdate :one
SELECT id, order_number, user_id, status, payment_status, payment_method, currency, email, phone, ship_city_id, ship_city_name, ship_address, ship_postcode, ship_recipient, shipping_method, subtotal, discount_total, shipping_total, tax_total, grand_total, comment, idempotency_key, created_at, updated_at, paid_at, cancelled_at, ship_provider, ship_tariff_code, ship_point_code, ship_min_days, ship_max_days, source FROM orders WHERE order_number = $1 LIMIT 1 FOR UPDATE
`

// Row-locks the order for a status transition. Transaction only.
func (q *Queries) GetByNumberForUpdate(ctx context.Context, orderNumber int64) (*models.Order, error) {
	row := q.db.QueryRow(ctx, getByNumberForUpdate, orderNumber)
	var i models.Order
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.UserID,
		&i.Status,
		&i.PaymentStatus,
		&i.PaymentMethod,
		&i.Currency,
		&i.Email,
		&i.Phone,
		&i.ShipCityID,
		&i.ShipCityName,
		&i.ShipAddress,
		&i.ShipPostcode,
		&i.ShipRecipient,
		&i.ShippingMethod,
		&i.Subtotal,
		&i.DiscountTotal,
		&i.ShippingTotal,
		&i.TaxTotal,
		&i.GrandTotal,
		&i.Comment,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaidAt,
		&i.CancelledAt,
		&i.ShipProvider,
		&i.ShipTariffCode,
		&i.ShipPointCode,
		&i.ShipMinDays,
		&i.ShipMaxDays,
		&i.Source,
	)
	return &i, err
}

const hasUserPurchasedVariant = `-- name: HasUserPurchasedVariant :one
SELECT o.id
FROM orders o
JOIN order_items oi ON oi.order_id = o.id
WHERE o.user_id = $1::uuid
  AND oi.variant_id = $2::uuid
  AND o.payment_status = 'paid'
  AND o.status NOT IN ('cancelled', 'refunded')
ORDER BY o.created_at DESC
LIMIT 1
`

type HasUserPurchasedVariantParams struct {
	UserID    uuid.UUID `db:"user_id" json:"user_id"`
	VariantID uuid.UUID `db:"variant_id" json:"variant_id"`
}

// Newest paid, non-cancelled/refunded order of the user that contains the
// variant. Gates review creation to actually-purchased variants; the returned
// order id is stored on the review.
func (q *Queries) HasUserPurchasedVariant(ctx context.Context, arg HasUserPurchasedVariantParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, hasUserPurchasedVariant, arg.UserID, arg.VariantID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listAdmin = `-- name: ListAdmin :many
SELECT id, order_number, user_id, status, payment_status, payment_method, currency, email, phone, ship_city_id, ship_city_name, ship_address, ship_postcode, ship_recipient, shipping_method, subtotal, discount_total, shipping_total, tax_total, grand_total, comment, idempotency_key, created_at, updated_at, paid_at, cancelled_at, ship_provider, ship_tariff_code, ship_point_code, ship_min_days, ship_max_days, source FROM orders
WHERE ($1::varchar IS NULL OR status = $1)
  AND ($2::varchar IS NULL OR payment_status = $2)
  AND ($3::varchar IS NULL OR source = $3)
  AND ($4::uuid IS NULL OR user_id = $4)
  AND ($5::timestamp IS NULL OR created_at >= $5)
  AND ($6::timestamp IS NULL OR created_at <= $6)
ORDER BY created_at DESC
LIMIT $8 OFFSET $7
`

type ListAdminParams struct {
	Status        pgtype.Text      `db:"status" json:"status"`
	PaymentStatus pgtype.Text      `db:"payment_status" json:"payment_status"`
	Source        pgtype.Text      `db:"source" json:"source"`
	UserID        uuid.NullUUID    `db:"user_id" json:"user_id"`
	CreatedFrom   pgtype.Timestamp `db:"created_from" json:"created_from"`
	CreatedTo     pgtype.Timestamp `db:"created_to" json:"created_to"`
	Offset        int32            `db:"offset" json:"offset"`
	Limit         int32            `db:"limit" json:"limit"`
}

// Every filter is optional (NULL = don't filter on it); used by the admin order list.
func (q *Queries) ListAdmin(ctx context.Context, arg ListAdminParams) ([]*models.Order, error) {
	rows, err := q.db.Query(ctx, listAdmin,
		arg.Status,
		arg.PaymentStatus,
		arg.Source,
		arg.UserID,
		arg.CreatedFrom,
		arg.CreatedTo,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*models.Order{}
	for rows.Next() {
		var i models.Order
		if err := rows.Scan(
			&i.ID,
			&i.OrderNumber,
			&i.UserID,
			&i.Status,
			&i.PaymentStatus,
			&i.PaymentMethod,
			&i.Currency,
			&i.Email,
			&i.Phone,
			&i.ShipCityID,
			&i.ShipCityName,
			&i.ShipAddress,
			&i.ShipPostcode,
			&i.ShipRecipient,
			&i.ShippingMethod,
			&i.Subtotal,
			&i.DiscountTotal,
			&i.ShippingTotal,
			&i.TaxTotal,
			&i.GrandTotal,
			&i.Comment,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PaidAt,
			&i.CancelledAt,
			&i.ShipProvider,
			&i.ShipTariffCode,
			&i.ShipPointCode,
			&i.ShipMinDays,
			&i.ShipMaxDays,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listByUser = `-- name: ListByUser :many
SELECT id, order_number, user_id, status, payment_status, payment_method, currency, email, phone, ship_city_id, ship_city_name, ship_address, ship_postcode, ship_recipient, shipping_method, subtotal, discount_total, shipping_total, tax_total, grand_total, comment, idempotency_key, created_at, updated_at, paid_at, cancelled_at, ship_provider, ship_tariff_code, ship_point_code, ship_min_days, ship_max_days, source FROM orders
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListByUserParams struct {
	UserID uuid.NullUUID `db:"user_id" json:"user_id"`
	Limit  int32         `db:"limit" json:"limit"`
	Offset int32         `db:"offset" json:"offset"`
}

func (q *Queries) ListByUser(ctx context.Context, arg ListByUserParams) ([]*models.Order, error) {
	rows, err := q.db.Query(ctx, listByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*models.Order{}
	for rows.Next() {
		var i models.Order
		if err := rows.Scan(
			&i.ID,
			&i.OrderNumber,
			&i.UserID,
			&i.Status,
			&i.PaymentStatus,
			&i.PaymentMethod,
			&i.Currency,
			&i.Email,
			&i.Phone,
			&i.ShipCityID,
			&i.ShipCityName,
			&i.ShipAddress,
			&i.ShipPostcode,
			&i.ShipRecipient,
			&i.ShippingMethod,
			&i.Subtotal,
			&i.DiscountTotal,
			&i.ShippingTotal,
			&i.TaxTotal,
			&i.GrandTotal,
			&i.Comment,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PaidAt,
			&i.CancelledAt,
			&i.ShipProvider,
			&i.ShipTariffCode,
			&i.ShipPointCode,
			&i.ShipMinDays,
			&i.ShipMaxDays,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredPending = `-- name: ListExpiredPending :many
SELECT id
FROM orders
WHERE status = 'pending'
  AND created_at < $1
ORDER BY created_at
LIMIT $2
FOR UPDATE SKIP LOCKED
`

type ListExpiredPendingParams struct {
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
	Limit     int32            `db:"limit" json:"limit"`
}

// Callers must run this inside a transaction; the row locks are held until commit.
func (q *Queries) ListExpiredPending(ctx context.Context, arg ListExpiredPendingParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listExpiredPending, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCancelled = `-- name: MarkCancelled :one
UPDATE orders
SET status = 'cancelled',
    cancelled_at = now(),
    updated_at = now()
WHERE id = $1
RETURNING id, order_number, user_id, status, payment_status, payment_method, currency, email, phone, ship_city_id, ship_city_name, ship_address, ship_postcode, ship_recipient, shipping_method, subtotal, discount_total, shipping_total, tax_total, grand_total, comment, idempotency_key, created_at, updated_at, paid_at, cancelled_at, ship_provider, ship_tariff_code, ship_point_code, ship_min_days, ship_max_days, source
`

func (q *Queries) MarkCancelled(ctx context.Context, id uuid.UUID) (*models.Order, error) {
	row := q.db.QueryRow(ctx, markCancelled, id)
	var i models.Order
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.UserID,
		&i.Status,
		&i.PaymentStatus,
		&i.PaymentMethod,
		&i.Currency,
		&i.Email,
		&i.Phone,
		&i.ShipCityID,
		&i.ShipCityName,
		&i.ShipAddress,
		&i.ShipPostcode,
		&i.ShipRecipient,
		&i.ShippingMethod,
		&i.Subtotal,
		&i.DiscountTotal,
		&i.ShippingTotal,
		&i.TaxTotal,
		&i.GrandTotal,
		&i.Comment,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaidAt,
		&i.CancelledAt,
		&i.ShipProvider,
		&i.ShipTariffCode,
		&i.ShipPointCode,
		&i.ShipMinDays,
		&i.ShipMaxDays,
		&i.Source,
	)
	return &i, err
}

const markPaid = `-- name: MarkPaid :one
UPDATE orders
SET status = $2,
    payment_status = 'paid',
    payment_method = $3,
    paid_at = now(),
    updated_at = now()
WHERE id = $1
RETURNING id, order_number, user_id, status, payment_status, payment_method, currency, email, phone, ship_city_id, ship_city_name, ship_address, ship_postcode, ship_recipient, shipping_method, subtotal, discount_total, shipping_total, tax_total, grand_total, comment, idempotency_key, created_at, updated_at, paid_at, cancelled_at, ship_provider, ship_tariff_code, ship_point_code, ship_min_days, ship_max_days, source
`

type MarkPaidParams struct {
	ID            uuid.UUID   `db:"id" json:"id"`
	Status        string      `db:"status" json:"status"`
	PaymentMethod pgtype.Text `db:"payment_method" json:"payment_method"`
}

func (q *Queries) MarkPaid(ctx context.Context, arg MarkPaidParams) (*models.Order, error) {
	row := q.db.QueryRow(ctx, markPaid, arg.ID, arg.Status, arg.PaymentMethod)
	var i models.Order
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.UserID,
		&i.Status,
		&i.PaymentStatus,
		&i.PaymentMethod,
		&i.Currency,
		&i.Email,
		&i.Phone,
		&i.ShipCityID,
		&i.ShipCityName,
		&i.ShipAddress,
		&i.ShipPostcode,
		&i.ShipRecipient,
		&i.ShippingMethod,
		&i.Subtotal,
		&i.DiscountTotal,
		&i.ShippingTotal,
		&i.TaxTotal,
		&i.GrandTotal,
		&i.Comment,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaidAt,
		&i.CancelledAt,
		&i.ShipProvider,
		&i.ShipTariffCode,
		&i.ShipPointCode,
		&i.ShipMinDays,
		&i.ShipMaxDays,
		&i.Source,
	)
	return &i, err
}

const markRefunded = `-- name: MarkRefunded :one
UPDATE orders
SET status = 'refunded',
    payment_status = 'refunded',
    updated_at = now()
WHERE id = $1
RETURNING id, order_number, user_id, status, payment_status, payment_method, currency, email, phone, ship_city_id, ship_city_name, ship_address, ship_postcode, ship_recipient, shipping_method, subtotal, discount_total, shipping_total, tax_total, grand_total, comment, idempotency_key, created_at, updated_at, paid_at, cancelled_at, ship_provider, ship_tariff_code, ship_point_code, ship_min_days, ship_max_days, source
`

// Refund also clears the payment status back to 'refunded' (unlike a plain
// status transition, which never touches payment_status).
func (q *Queries) MarkRefunded(ctx context.Context, id uuid.UUID) (*models.Order, error) {
	row := q.db.QueryRow(ctx, markRefunded, id)
	var i models.Order
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.UserID,
		&i.Status,
		&i.PaymentStatus,
		&i.PaymentMethod,
		&i.Currency,
		&i.Email,
		&i.Phone,
		&i.ShipCityID,
		&i.ShipCityName,
		&i.ShipAddress,
		&i.ShipPostcode,
		&i.ShipRecipient,
		&i.ShippingMethod,
		&i.Subtotal,
		&i.DiscountTotal,
		&i.ShippingTotal,
		&i.TaxTotal,
		&i.GrandTotal,
		&i.Comment,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaidAt,
		&i.CancelledAt,
		&i.ShipProvider,
		&i.ShipTariffCode,
		&i.ShipPointCode,
		&i.ShipMinDays,
		&i.ShipMaxDays,
		&i.Source,
	)
	return &i, err
}

const updateDetails = `-- name: UpdateDetails :one
UPDATE orders
SET status          = $2,
    email           = $3,
    phone           = $4,
    ship_city_id    = $5,
    ship_city_name  = $6,
    ship_address    = $7,
    ship_postcode   = $8,
    ship_recipient  = $9,
    shipping_method = $10,
    ship_provider   = $11,
    ship_tariff_code = $12,
    ship_point_code = $13,
    ship_min_days   = $14,
    ship_max_days   = $15,
    payment_method  = $16,
    comment         = $17,
    shipping_total  = $18,
    grand_total     = $19,
    updated_at      = now()
WHERE id = $1
RETURNING id, order_number, user_id, status, payment_status, payment_method, currency, email, phone, ship_city_id, ship_city_name, ship_address, ship_postcode, ship_recipient, shipping_method, subtotal, discount_total, shipping_total, tax_total, grand_total, comment, idempotency_key, created_at, updated_at, paid_at, cancelled_at, ship_provider, ship_tariff_code, ship_point_code, ship_min_days, ship_max_days, source
`

type UpdateDetailsParams struct {
	ID             uuid.UUID       `db:"id" json:"id"`
	Status         string          `db:"status" json:"status"`
	Email          string          `db:"email" json:"email"`
	Phone          pgtype.Text     `db:"phone" json:"phone"`
	ShipCityID     uuid.NullUUID   `db:"ship_city_id" json:"ship_city_id"`
	ShipCityName   string          `db:"ship_city_name" json:"ship_city_name"`
	ShipAddress    string          `db:"ship_address" json:"ship_address"`
	ShipPostcode   pgtype.Text     `db:"ship_postcode" json:"ship_postcode"`
	ShipRecipient  string          `db:"ship_recipient" json:"ship_recipient"`
	ShippingMethod pgtype.Text     `db:"shipping_method" json:"shipping_method"`
	ShipProvider   pgtype.Text     `db:"ship_provider" json:"ship_provider"`
	ShipTariffCode pgtype.Text     `db:"ship_tariff_code" json:"ship_tariff_code"`
	ShipPointCode  pgtype.Text     `db:"ship_point_code" json:"ship_point_code"`
	ShipMinDays    pgtype.Int4     `db:"ship_min_days" json:"ship_min_days"`
	ShipMaxDays    pgtype.Int4     `db:"ship_max_days" json:"ship_max_days"`
	PaymentMethod  pgtype.Text     `db:"payment_method" json:"payment_method"`
	Comment        pgtype.Text     `db:"comment" json:"comment"`
	ShippingTotal  decimal.Decimal `db:"shipping_total" json:"shipping_total"`
	GrandTotal     decimal.Decimal `db:"grand_total" json:"grand_total"`
}

// Admin order edit: contact, shipping address + carrier snapshot, payment method,
// comment and the money fields that shipping/status changes affect. Item lines and
// their prices are never touched here. Transaction only (row must be locked).
func (q *Queries) UpdateDetails(ctx context.Context, arg UpdateDetailsParams) (*models.Order, error) {
	row := q.db.QueryRow(ctx, updateDetails,
		arg.ID,
		arg.Status,
		arg.Email,
		arg.Phone,
		arg.ShipCityID,
		arg.ShipCityName,
		arg.ShipAddress,
		arg.ShipPostcode,
		arg.ShipRecipient,
		arg.ShippingMethod,
		arg.ShipProvider,
		arg.ShipTariffCode,
		arg.ShipPointCode,
		arg.ShipMinDays,
		arg.ShipMaxDays,
		arg.PaymentMethod,
		arg.Comment,
		arg.ShippingTotal,
		arg.GrandTotal,
	)
	var i models.Order
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.UserID,
		&i.Status,
		&i.PaymentStatus,
		&i.PaymentMethod,
		&i.Currency,
		&i.Email,
		&i.Phone,
		&i.ShipCityID,
		&i.ShipCityName,
		&i.ShipAddress,
		&i.ShipPostcode,
		&i.ShipRecipient,
		&i.ShippingMethod,
		&i.Subtotal,
		&i.DiscountTotal,
		&i.ShippingTotal,
		&i.TaxTotal,
		&i.GrandTotal,
		&i.Comment,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaidAt,
		&i.CancelledAt,
		&i.ShipProvider,
		&i.ShipTariffCode,
		&i.ShipPointCode,
		&i.ShipMinDays,
		&i.ShipMaxDays,
		&i.Source,
	)
	return &i, err
}

const updateStatus = `-- name: UpdateStatus :one
UPDATE orders
SET status = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, order_number, user_id, status, payment_status, payment_method, currency, email, phone, ship_city_id, ship_city_name, ship_address, ship_postcode, ship_recipient, shipping_method, subtotal, discount_total, shipping_total, tax_total, grand_total, comment, idempotency_key, created_at, updated_at, paid_at, cancelled_at, ship_provider, ship_tariff_code, ship_point_code, ship_min_days, ship_max_days, source
`

type UpdateStatusParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	Status string    `db:"status" json:"status"`
}

func (q *Queries) UpdateStatus(ctx context.Context, arg UpdateStatusParams) (*models.Order, error) {
	row := q.db.QueryRow(ctx, updateStatus, arg.ID, arg.Status)
	var i models.Order
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.UserID,
		&i.Status,
		&i.PaymentStatus,
		&i.PaymentMethod,
		&i.Currency,
		&i.Email,
		&i.Phone,
		&i.ShipCityID,
		&i.ShipCityName,
		&i.ShipAddress,
		&i.ShipPostcode,
		&i.ShipRecipient,
		&i.ShippingMethod,
		&i.Subtotal,
		&i.DiscountTotal,
		&i.ShippingTotal,
		&i.TaxTotal,
		&i.GrandTotal,
		&i.Comment,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaidAt,
		&i.CancelledAt,
		&i.ShipProvider,
		&i.ShipTariffCode,
		&i.ShipPointCode,
		&i.ShipMinDays,
		&i.ShipMaxDays,
		&i.Source,
	)
	return &i, err
}
