// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders_gen.sql

package repository_orders

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
	"github.com/stickpro/go-store/internal/models"
)

const create = `-- name: Create :one
INSERT INTO orders (user_id, status, payment_status, payment_method, currency, email, phone, ship_city_id, ship_city_name, ship_address, ship_postcode, ship_recipient, shipping_method, subtotal, discount_total, shipping_total, tax_total, grand_total, comment, idempotency_key, ship_provider, ship_tariff_code, ship_point_code, ship_min_days, ship_max_days)
	VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25)
	RETURNING id, order_number, user_id, status, payment_status, payment_method, currency, email, phone, ship_city_id, ship_city_name, ship_address, ship_postcode, ship_recipient, shipping_method, subtotal, discount_total, shipping_total, tax_total, grand_total, comment, idempotency_key, created_at, updated_at, paid_at, cancelled_at, ship_provider, ship_tariff_code, ship_point_code, ship_min_days, ship_max_days
`

type CreateParams struct {
	UserID         uuid.NullUUID   `db:"user_id" json:"user_id"`
	Status         string          `db:"status" json:"status"`
	PaymentStatus  string          `db:"payment_status" json:"payment_status"`
	PaymentMethod  pgtype.Text     `db:"payment_method" json:"payment_method"`
	Currency       string          `db:"currency" json:"currency"`
	Email          string          `db:"email" json:"email"`
	Phone          pgtype.Text     `db:"phone" json:"phone"`
	ShipCityID     uuid.NullUUID   `db:"ship_city_id" json:"ship_city_id"`
	ShipCityName   string          `db:"ship_city_name" json:"ship_city_name"`
	ShipAddress    string          `db:"ship_address" json:"ship_address"`
	ShipPostcode   pgtype.Text     `db:"ship_postcode" json:"ship_postcode"`
	ShipRecipient  string          `db:"ship_recipient" json:"ship_recipient"`
	ShippingMethod pgtype.Text     `db:"shipping_method" json:"shipping_method"`
	Subtotal       decimal.Decimal `db:"subtotal" json:"subtotal"`
	DiscountTotal  decimal.Decimal `db:"discount_total" json:"discount_total"`
	ShippingTotal  decimal.Decimal `db:"shipping_total" json:"shipping_total"`
	TaxTotal       decimal.Decimal `db:"tax_total" json:"tax_total"`
	GrandTotal     decimal.Decimal `db:"grand_total" json:"grand_total"`
	Comment        pgtype.Text     `db:"comment" json:"comment"`
	IdempotencyKey pgtype.Text     `db:"idempotency_key" json:"idempotency_key"`
	ShipProvider   pgtype.Text     `db:"ship_provider" json:"ship_provider"`
	ShipTariffCode pgtype.Text     `db:"ship_tariff_code" json:"ship_tariff_code"`
	ShipPointCode  pgtype.Text     `db:"ship_point_code" json:"ship_point_code"`
	ShipMinDays    pgtype.Int4     `db:"ship_min_days" json:"ship_min_days"`
	ShipMaxDays    pgtype.Int4     `db:"ship_max_days" json:"ship_max_days"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (*models.Order, error) {
	row := q.db.QueryRow(ctx, create,
		arg.UserID,
		arg.Status,
		arg.PaymentStatus,
		arg.PaymentMethod,
		arg.Currency,
		arg.Email,
		arg.Phone,
		arg.ShipCityID,
		arg.ShipCityName,
		arg.ShipAddress,
		arg.ShipPostcode,
		arg.ShipRecipient,
		arg.ShippingMethod,
		arg.Subtotal,
		arg.DiscountTotal,
		arg.ShippingTotal,
		arg.TaxTotal,
		arg.GrandTotal,
		arg.Comment,
		arg.IdempotencyKey,
		arg.ShipProvider,
		arg.ShipTariffCode,
		arg.ShipPointCode,
		arg.ShipMinDays,
		arg.ShipMaxDays,
	)
	var i models.Order
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.UserID,
		&i.Status,
		&i.PaymentStatus,
		&i.PaymentMethod,
		&i.Currency,
		&i.Email,
		&i.Phone,
		&i.ShipCityID,
		&i.ShipCityName,
		&i.ShipAddress,
		&i.ShipPostcode,
		&i.ShipRecipient,
		&i.ShippingMethod,
		&i.Subtotal,
		&i.DiscountTotal,
		&i.ShippingTotal,
		&i.TaxTotal,
		&i.GrandTotal,
		&i.Comment,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaidAt,
		&i.CancelledAt,
		&i.ShipProvider,
		&i.ShipTariffCode,
		&i.ShipPointCode,
		&i.ShipMinDays,
		&i.ShipMaxDays,
	)
	return &i, err
}

const get = `-- name: Get :one
SELECT id, order_number, user_id, status, payment_status, payment_method, currency, email, phone, ship_city_id, ship_city_name, ship_address, ship_postcode, ship_recipient, shipping_method, subtotal, discount_total, shipping_total, tax_total, grand_total, comment, idempotency_key, created_at, updated_at, paid_at, cancelled_at, ship_provider, ship_tariff_code, ship_point_code, ship_min_days, ship_max_days FROM orders WHERE id=$1 LIMIT 1
`

func (q *Queries) Get(ctx context.Context, id uuid.UUID) (*models.Order, error) {
	row := q.db.QueryRow(ctx, get, id)
	var i models.Order
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.UserID,
		&i.Status,
		&i.PaymentStatus,
		&i.PaymentMethod,
		&i.Currency,
		&i.Email,
		&i.Phone,
		&i.ShipCityID,
		&i.ShipCityName,
		&i.ShipAddress,
		&i.ShipPostcode,
		&i.ShipRecipient,
		&i.ShippingMethod,
		&i.Subtotal,
		&i.DiscountTotal,
		&i.ShippingTotal,
		&i.TaxTotal,
		&i.GrandTotal,
		&i.Comment,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaidAt,
		&i.CancelledAt,
		&i.ShipProvider,
		&i.ShipTariffCode,
		&i.ShipPointCode,
		&i.ShipMinDays,
		&i.ShipMaxDays,
	)
	return &i, err
}
