// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository_orders

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/stickpro/go-store/internal/models"
)

type Querier interface {
	CountByUser(ctx context.Context, userID uuid.NullUUID) (int64, error)
	Create(ctx context.Context, arg CreateParams) (*models.Order, error)
	Get(ctx context.Context, id uuid.UUID) (*models.Order, error)
	GetByIdempotencyKey(ctx context.Context, idempotencyKey pgtype.Text) (*models.Order, error)
	GetByNumber(ctx context.Context, orderNumber int64) (*models.Order, error)
	ListByUser(ctx context.Context, arg ListByUserParams) ([]*models.Order, error)
	// Callers must run this inside a transaction; the row locks are held until commit.
	ListExpiredPending(ctx context.Context, arg ListExpiredPendingParams) ([]uuid.UUID, error)
	MarkCancelled(ctx context.Context, id uuid.UUID) (*models.Order, error)
	MarkPaid(ctx context.Context, arg MarkPaidParams) (*models.Order, error)
	UpdateStatus(ctx context.Context, arg UpdateStatusParams) (*models.Order, error)
}

var _ Querier = (*Queries)(nil)
