// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository_attribute_values

import (
	"context"

	"github.com/google/uuid"
	"github.com/stickpro/go-store/internal/models"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) (*models.AttributeValue, error)
	Delete(ctx context.Context, id uuid.UUID) error
	GetAll(ctx context.Context, arg GetAllParams) ([]*models.AttributeValue, error)
	GetByAttributeID(ctx context.Context, attributeID uuid.UUID) ([]*models.AttributeValue, error)
	GetByID(ctx context.Context, id uuid.UUID) (*models.AttributeValue, error)
	GetOrCreate(ctx context.Context, arg GetOrCreateParams) (*models.AttributeValue, error)
	GetWithUsageCount(ctx context.Context, attributeID uuid.UUID) ([]*GetWithUsageCountRow, error)
	Update(ctx context.Context, arg UpdateParams) (*models.AttributeValue, error)
}

var _ Querier = (*Queries)(nil)
