// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attribute_groups.sql

package repository_attribute_groups

import (
	"context"

	"github.com/google/uuid"
	"github.com/stickpro/go-store/internal/models"
)

const getByID = `-- name: GetByID :one
SELECT id, name, description, created_at, updated_at FROM attribute_groups WHERE id = $1 LIMIT 1
`

func (q *Queries) GetByID(ctx context.Context, id uuid.UUID) (*models.AttributeGroup, error) {
	row := q.db.QueryRow(ctx, getByID, id)
	var i models.AttributeGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
