// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository_attribute_groups

import (
	"context"

	"github.com/google/uuid"
	"github.com/stickpro/go-store/internal/models"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) (*models.AttributeGroup, error)
	Delete(ctx context.Context, id uuid.UUID) error
	GetAll(ctx context.Context, arg GetAllParams) ([]*models.AttributeGroup, error)
	GetByID(ctx context.Context, id uuid.UUID) (*models.AttributeGroup, error)
	Update(ctx context.Context, arg UpdateParams) (*models.AttributeGroup, error)
}

var _ Querier = (*Queries)(nil)
