// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package repository_payments

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
	"github.com/stickpro/go-store/internal/models"
)

const applyRefund = `-- name: ApplyRefund :one
UPDATE payments
SET refunded_amount = $2,
    status          = $3,
    updated_at      = now()
WHERE id = $1
RETURNING id, order_id, provider, provider_payment_id, status, amount, currency, payment_url, raw_init_response, raw_last_notification, created_at, updated_at, refunded_amount
`

type ApplyRefundParams struct {
	ID             uuid.UUID       `db:"id" json:"id"`
	RefundedAmount decimal.Decimal `db:"refunded_amount" json:"refunded_amount"`
	Status         string          `db:"status" json:"status"`
}

func (q *Queries) ApplyRefund(ctx context.Context, arg ApplyRefundParams) (*models.Payment, error) {
	row := q.db.QueryRow(ctx, applyRefund, arg.ID, arg.RefundedAmount, arg.Status)
	var i models.Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.Status,
		&i.Amount,
		&i.Currency,
		&i.PaymentUrl,
		&i.RawInitResponse,
		&i.RawLastNotification,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RefundedAmount,
	)
	return &i, err
}

const getByID = `-- name: GetByID :one
SELECT id, order_id, provider, provider_payment_id, status, amount, currency, payment_url, raw_init_response, raw_last_notification, created_at, updated_at, refunded_amount FROM payments WHERE id = $1 LIMIT 1
`

func (q *Queries) GetByID(ctx context.Context, id uuid.UUID) (*models.Payment, error) {
	row := q.db.QueryRow(ctx, getByID, id)
	var i models.Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.Status,
		&i.Amount,
		&i.Currency,
		&i.PaymentUrl,
		&i.RawInitResponse,
		&i.RawLastNotification,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RefundedAmount,
	)
	return &i, err
}

const getByIDForUpdate = `-- name: GetByIDForUpdate :one
SELECT id, order_id, provider, provider_payment_id, status, amount, currency, payment_url, raw_init_response, raw_last_notification, created_at, updated_at, refunded_amount FROM payments WHERE id = $1 LIMIT 1 FOR UPDATE
`

func (q *Queries) GetByIDForUpdate(ctx context.Context, id uuid.UUID) (*models.Payment, error) {
	row := q.db.QueryRow(ctx, getByIDForUpdate, id)
	var i models.Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.Status,
		&i.Amount,
		&i.Currency,
		&i.PaymentUrl,
		&i.RawInitResponse,
		&i.RawLastNotification,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RefundedAmount,
	)
	return &i, err
}

const getByProviderPaymentID = `-- name: GetByProviderPaymentID :one
SELECT id, order_id, provider, provider_payment_id, status, amount, currency, payment_url, raw_init_response, raw_last_notification, created_at, updated_at, refunded_amount FROM payments WHERE provider = $1 AND provider_payment_id = $2 LIMIT 1
`

type GetByProviderPaymentIDParams struct {
	Provider          string      `db:"provider" json:"provider"`
	ProviderPaymentID pgtype.Text `db:"provider_payment_id" json:"provider_payment_id"`
}

func (q *Queries) GetByProviderPaymentID(ctx context.Context, arg GetByProviderPaymentIDParams) (*models.Payment, error) {
	row := q.db.QueryRow(ctx, getByProviderPaymentID, arg.Provider, arg.ProviderPaymentID)
	var i models.Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.Status,
		&i.Amount,
		&i.Currency,
		&i.PaymentUrl,
		&i.RawInitResponse,
		&i.RawLastNotification,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RefundedAmount,
	)
	return &i, err
}

const getLatestByOrderID = `-- name: GetLatestByOrderID :one
SELECT id, order_id, provider, provider_payment_id, status, amount, currency, payment_url, raw_init_response, raw_last_notification, created_at, updated_at, refunded_amount FROM payments WHERE order_id = $1 ORDER BY created_at DESC LIMIT 1
`

// Most recent payment attempt for the order (a customer may retry after a
// failed/expired attempt, so an order can have more than one row).
func (q *Queries) GetLatestByOrderID(ctx context.Context, orderID uuid.UUID) (*models.Payment, error) {
	row := q.db.QueryRow(ctx, getLatestByOrderID, orderID)
	var i models.Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.Status,
		&i.Amount,
		&i.Currency,
		&i.PaymentUrl,
		&i.RawInitResponse,
		&i.RawLastNotification,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RefundedAmount,
	)
	return &i, err
}

const getRefundableByOrderIDForUpdate = `-- name: GetRefundableByOrderIDForUpdate :one
SELECT id, order_id, provider, provider_payment_id, status, amount, currency, payment_url, raw_init_response, raw_last_notification, created_at, updated_at, refunded_amount FROM payments
WHERE order_id = $1 AND status IN ('confirmed', 'partially_refunded')
ORDER BY created_at DESC
LIMIT 1
FOR UPDATE
`

// The order's captured payment that still has money left to refund, locked
// so concurrent refunds see each other's pending rows.
func (q *Queries) GetRefundableByOrderIDForUpdate(ctx context.Context, orderID uuid.UUID) (*models.Payment, error) {
	row := q.db.QueryRow(ctx, getRefundableByOrderIDForUpdate, orderID)
	var i models.Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.Status,
		&i.Amount,
		&i.Currency,
		&i.PaymentUrl,
		&i.RawInitResponse,
		&i.RawLastNotification,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RefundedAmount,
	)
	return &i, err
}

const listByOrderID = `-- name: ListByOrderID :many
SELECT id, order_id, provider, provider_payment_id, status, amount, currency, payment_url, raw_init_response, raw_last_notification, created_at, updated_at, refunded_amount FROM payments WHERE order_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListByOrderID(ctx context.Context, orderID uuid.UUID) ([]*models.Payment, error) {
	rows, err := q.db.Query(ctx, listByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*models.Payment{}
	for rows.Next() {
		var i models.Payment
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.Provider,
			&i.ProviderPaymentID,
			&i.Status,
			&i.Amount,
			&i.Currency,
			&i.PaymentUrl,
			&i.RawInitResponse,
			&i.RawLastNotification,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RefundedAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAfterInit = `-- name: UpdateAfterInit :one
UPDATE payments
SET provider_payment_id = $2,
    payment_url         = $3,
    status               = $4,
    raw_init_response    = $5,
    updated_at           = now()
WHERE id = $1
RETURNING id, order_id, provider, provider_payment_id, status, amount, currency, payment_url, raw_init_response, raw_last_notification, created_at, updated_at, refunded_amount
`

type UpdateAfterInitParams struct {
	ID                uuid.UUID   `db:"id" json:"id"`
	ProviderPaymentID pgtype.Text `db:"provider_payment_id" json:"provider_payment_id"`
	PaymentUrl        pgtype.Text `db:"payment_url" json:"payment_url"`
	Status            string      `db:"status" json:"status"`
	RawInitResponse   []byte      `db:"raw_init_response" json:"raw_init_response"`
}

// Fills in what the provider's Init call returned: its own payment id, the
// URL to redirect the customer to, and the raw response for audit/debugging.
func (q *Queries) UpdateAfterInit(ctx context.Context, arg UpdateAfterInitParams) (*models.Payment, error) {
	row := q.db.QueryRow(ctx, updateAfterInit,
		arg.ID,
		arg.ProviderPaymentID,
		arg.PaymentUrl,
		arg.Status,
		arg.RawInitResponse,
	)
	var i models.Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.Status,
		&i.Amount,
		&i.Currency,
		&i.PaymentUrl,
		&i.RawInitResponse,
		&i.RawLastNotification,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RefundedAmount,
	)
	return &i, err
}

const updateStatus = `-- name: UpdateStatus :one
UPDATE payments
SET status                = $2,
    raw_last_notification = $3,
    updated_at             = now()
WHERE id = $1
RETURNING id, order_id, provider, provider_payment_id, status, amount, currency, payment_url, raw_init_response, raw_last_notification, created_at, updated_at, refunded_amount
`

type UpdateStatusParams struct {
	ID                  uuid.UUID `db:"id" json:"id"`
	Status              string    `db:"status" json:"status"`
	RawLastNotification []byte    `db:"raw_last_notification" json:"raw_last_notification"`
}

// Transitions a payment on a provider webhook/response (notification or
// cancel/refund). raw_last_notification is overwritten with the latest
// payload for audit/debugging.
func (q *Queries) UpdateStatus(ctx context.Context, arg UpdateStatusParams) (*models.Payment, error) {
	row := q.db.QueryRow(ctx, updateStatus, arg.ID, arg.Status, arg.RawLastNotification)
	var i models.Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.Status,
		&i.Amount,
		&i.Currency,
		&i.PaymentUrl,
		&i.RawInitResponse,
		&i.RawLastNotification,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RefundedAmount,
	)
	return &i, err
}
