// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments_gen.sql

package repository_payments

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
	"github.com/stickpro/go-store/internal/models"
)

const create = `-- name: Create :one
INSERT INTO payments (order_id, provider, provider_payment_id, status, amount, currency, payment_url, raw_init_response, raw_last_notification, created_at)
	VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, now())
	RETURNING id, order_id, provider, provider_payment_id, status, amount, currency, payment_url, raw_init_response, raw_last_notification, created_at, updated_at, refunded_amount
`

type CreateParams struct {
	OrderID             uuid.UUID       `db:"order_id" json:"order_id"`
	Provider            string          `db:"provider" json:"provider"`
	ProviderPaymentID   pgtype.Text     `db:"provider_payment_id" json:"provider_payment_id"`
	Status              string          `db:"status" json:"status"`
	Amount              decimal.Decimal `db:"amount" json:"amount"`
	Currency            string          `db:"currency" json:"currency"`
	PaymentUrl          pgtype.Text     `db:"payment_url" json:"payment_url"`
	RawInitResponse     []byte          `db:"raw_init_response" json:"raw_init_response"`
	RawLastNotification []byte          `db:"raw_last_notification" json:"raw_last_notification"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (*models.Payment, error) {
	row := q.db.QueryRow(ctx, create,
		arg.OrderID,
		arg.Provider,
		arg.ProviderPaymentID,
		arg.Status,
		arg.Amount,
		arg.Currency,
		arg.PaymentUrl,
		arg.RawInitResponse,
		arg.RawLastNotification,
	)
	var i models.Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.Status,
		&i.Amount,
		&i.Currency,
		&i.PaymentUrl,
		&i.RawInitResponse,
		&i.RawLastNotification,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RefundedAmount,
	)
	return &i, err
}

const delete = `-- name: Delete :exec
DELETE FROM payments WHERE id=$1
`

func (q *Queries) Delete(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, delete, id)
	return err
}
