// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository_payments

import (
	"context"

	"github.com/google/uuid"
	"github.com/stickpro/go-store/internal/models"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) (*models.Payment, error)
	Delete(ctx context.Context, id uuid.UUID) error
	GetByID(ctx context.Context, id uuid.UUID) (*models.Payment, error)
	GetByProviderPaymentID(ctx context.Context, arg GetByProviderPaymentIDParams) (*models.Payment, error)
	// Most recent payment attempt for the order (a customer may retry after a
	// failed/expired attempt, so an order can have more than one row).
	GetLatestByOrderID(ctx context.Context, orderID uuid.UUID) (*models.Payment, error)
	ListByOrderID(ctx context.Context, orderID uuid.UUID) ([]*models.Payment, error)
	// Fills in what the provider's Init call returned: its own payment id, the
	// URL to redirect the customer to, and the raw response for audit/debugging.
	UpdateAfterInit(ctx context.Context, arg UpdateAfterInitParams) (*models.Payment, error)
	// Transitions a payment on a provider webhook/response (notification or
	// cancel/refund). raw_last_notification is overwritten with the latest
	// payload for audit/debugging.
	UpdateStatus(ctx context.Context, arg UpdateStatusParams) (*models.Payment, error)
}

var _ Querier = (*Queries)(nil)
