// Code generated by pgxgen. DO NOT EDIT.
package models

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
	"github.com/stickpro/go-store/internal/constant"
)

type Attribute struct {
	ID               uuid.UUID        `db:"id" json:"id"`
	AttributeGroupID uuid.NullUUID    `db:"attribute_group_id" json:"attribute_group_id"`
	Name             string           `db:"name" json:"name"`
	Slug             string           `db:"slug" json:"slug"`
	Type             string           `db:"type" json:"type"`
	Unit             pgtype.Text      `db:"unit" json:"unit"`
	IsFilterable     pgtype.Bool      `db:"is_filterable" json:"is_filterable"`
	IsVisible        pgtype.Bool      `db:"is_visible" json:"is_visible"`
	IsRequired       pgtype.Bool      `db:"is_required" json:"is_required"`
	SortOrder        pgtype.Int4      `db:"sort_order" json:"sort_order"`
	CreatedAt        pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamp `db:"updated_at" json:"updated_at"`
} //	@name	Attribute

type AttributeGroup struct {
	ID          uuid.UUID        `db:"id" json:"id"`
	Name        string           `db:"name" json:"name"`
	Slug        string           `db:"slug" json:"slug"`
	Description pgtype.Text      `db:"description" json:"description"`
	CreatedAt   pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamp `db:"updated_at" json:"updated_at"`
} //	@name	AttributeGroup

type AttributeValue struct {
	ID              uuid.UUID           `db:"id" json:"id"`
	AttributeID     uuid.UUID           `db:"attribute_id" json:"attribute_id"`
	Value           string              `db:"value" json:"value"`
	ValueNormalized pgtype.Text         `db:"value_normalized" json:"value_normalized"`
	ValueNumeric    decimal.NullDecimal `db:"value_numeric" json:"value_numeric"`
	DisplayOrder    pgtype.Int4         `db:"display_order" json:"display_order"`
	IsActive        pgtype.Bool         `db:"is_active" json:"is_active"`
	CreatedAt       pgtype.Timestamp    `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamp    `db:"updated_at" json:"updated_at"`
} //	@name	AttributeValue

type Category struct {
	ID              uuid.UUID        `db:"id" json:"id"`
	ParentID        uuid.NullUUID    `db:"parent_id" json:"parent_id"`
	Name            string           `db:"name" json:"name"`
	Slug            string           `db:"slug" json:"slug"`
	Description     pgtype.Text      `db:"description" json:"description"`
	ImagePath       pgtype.Text      `db:"image_path" json:"image_path"`
	MetaTitle       pgtype.Text      `db:"meta_title" json:"meta_title"`
	MetaH1          pgtype.Text      `db:"meta_h1" json:"meta_h1"`
	MetaDescription pgtype.Text      `db:"meta_description" json:"meta_description"`
	MetaKeyword     pgtype.Text      `db:"meta_keyword" json:"meta_keyword"`
	IsEnable        bool             `db:"is_enable" json:"is_enable"`
	CreatedAt       pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamp `db:"updated_at" json:"updated_at"`
} //	@name	Category

type CategoryPath struct {
	AncestorID   uuid.UUID `db:"ancestor_id" json:"ancestor_id"`
	DescendantID uuid.UUID `db:"descendant_id" json:"descendant_id"`
	Depth        int32     `db:"depth" json:"depth"`
} //	@name	CategoryPath

type City struct {
	ID              uuid.UUID       `db:"id" json:"id"`
	Address         string          `db:"address" json:"address"`
	PostalCode      string          `db:"postal_code" json:"postal_code"`
	Country         string          `db:"country" json:"country"`
	FederalDistrict string          `db:"federal_district" json:"federal_district"`
	RegionType      string          `db:"region_type" json:"region_type"`
	Region          string          `db:"region" json:"region"`
	AreaType        pgtype.Text     `db:"area_type" json:"area_type"`
	Area            pgtype.Text     `db:"area" json:"area"`
	CityType        string          `db:"city_type" json:"city_type"`
	City            string          `db:"city" json:"city"`
	SettlementType  pgtype.Text     `db:"settlement_type" json:"settlement_type"`
	Settlement      pgtype.Text     `db:"settlement" json:"settlement"`
	KladrID         string          `db:"kladr_id" json:"kladr_id"`
	FiasID          uuid.UUID       `db:"fias_id" json:"fias_id"`
	FiasLevel       int16           `db:"fias_level" json:"fias_level"`
	CapitalMarker   int16           `db:"capital_marker" json:"capital_marker"`
	Okato           string          `db:"okato" json:"okato"`
	Oktmo           string          `db:"oktmo" json:"oktmo"`
	TaxOffice       string          `db:"tax_office" json:"tax_office"`
	Timezone        string          `db:"timezone" json:"timezone"`
	GeoLat          decimal.Decimal `db:"geo_lat" json:"geo_lat"`
	GeoLon          decimal.Decimal `db:"geo_lon" json:"geo_lon"`
	Population      int64           `db:"population" json:"population"`
	FoundationYear  int16           `db:"foundation_year" json:"foundation_year"`
} //	@name	City

type Collection struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	Name        string             `db:"name" json:"name"`
	Description pgtype.Text        `db:"description" json:"description"`
	Slug        string             `db:"slug" json:"slug"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
} //	@name	Collection

type CollectionVariant struct {
	CollectionID uuid.UUID `db:"collection_id" json:"collection_id"`
	VariantID    uuid.UUID `db:"variant_id" json:"variant_id"`
} //	@name	CollectionVariant

type Manufacturer struct {
	ID              uuid.UUID        `db:"id" json:"id"`
	Name            string           `db:"name" json:"name"`
	Slug            string           `db:"slug" json:"slug"`
	Description     pgtype.Text      `db:"description" json:"description"`
	ImagePath       pgtype.Text      `db:"image_path" json:"image_path"`
	MetaTitle       pgtype.Text      `db:"meta_title" json:"meta_title"`
	MetaH1          pgtype.Text      `db:"meta_h1" json:"meta_h1"`
	MetaDescription pgtype.Text      `db:"meta_description" json:"meta_description"`
	MetaKeyword     pgtype.Text      `db:"meta_keyword" json:"meta_keyword"`
	IsEnable        bool             `db:"is_enable" json:"is_enable"`
	CreatedAt       pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamp `db:"updated_at" json:"updated_at"`
} //	@name	Manufacturer

type Medium struct {
	ID        uuid.UUID        `db:"id" json:"id"`
	Name      string           `db:"name" json:"name"`
	Path      string           `db:"path" json:"path"`
	FileName  string           `db:"file_name" json:"file_name"`
	MimeType  string           `db:"mime_type" json:"mime_type"`
	DiskType  string           `db:"disk_type" json:"disk_type"`
	Size      int64            `db:"size" json:"size"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
	SourceUrl pgtype.Text      `db:"source_url" json:"source_url"`
	Width     int32            `db:"width" json:"width"`
	Height    int32            `db:"height" json:"height"`
} //	@name	Medium

type Order struct {
	ID             uuid.UUID        `db:"id" json:"id"`
	OrderNumber    int64            `db:"order_number" json:"order_number"`
	UserID         uuid.NullUUID    `db:"user_id" json:"user_id"`
	Status         string           `db:"status" json:"status"`
	PaymentStatus  string           `db:"payment_status" json:"payment_status"`
	PaymentMethod  pgtype.Text      `db:"payment_method" json:"payment_method"`
	Currency       string           `db:"currency" json:"currency"`
	Email          string           `db:"email" json:"email"`
	Phone          pgtype.Text      `db:"phone" json:"phone"`
	ShipCityID     uuid.NullUUID    `db:"ship_city_id" json:"ship_city_id"`
	ShipCityName   string           `db:"ship_city_name" json:"ship_city_name"`
	ShipAddress    string           `db:"ship_address" json:"ship_address"`
	ShipPostcode   pgtype.Text      `db:"ship_postcode" json:"ship_postcode"`
	ShipRecipient  string           `db:"ship_recipient" json:"ship_recipient"`
	ShippingMethod pgtype.Text      `db:"shipping_method" json:"shipping_method"`
	Subtotal       decimal.Decimal  `db:"subtotal" json:"subtotal"`
	DiscountTotal  decimal.Decimal  `db:"discount_total" json:"discount_total"`
	ShippingTotal  decimal.Decimal  `db:"shipping_total" json:"shipping_total"`
	TaxTotal       decimal.Decimal  `db:"tax_total" json:"tax_total"`
	GrandTotal     decimal.Decimal  `db:"grand_total" json:"grand_total"`
	Comment        pgtype.Text      `db:"comment" json:"comment"`
	IdempotencyKey pgtype.Text      `db:"idempotency_key" json:"idempotency_key"`
	CreatedAt      pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	PaidAt         pgtype.Timestamp `db:"paid_at" json:"paid_at"`
	CancelledAt    pgtype.Timestamp `db:"cancelled_at" json:"cancelled_at"`
	ShipProvider   pgtype.Text      `db:"ship_provider" json:"ship_provider"`
	ShipTariffCode pgtype.Text      `db:"ship_tariff_code" json:"ship_tariff_code"`
	ShipPointCode  pgtype.Text      `db:"ship_point_code" json:"ship_point_code"`
	ShipMinDays    pgtype.Int4      `db:"ship_min_days" json:"ship_min_days"`
	ShipMaxDays    pgtype.Int4      `db:"ship_max_days" json:"ship_max_days"`
} //	@name	Order

type OrderItem struct {
	ID        uuid.UUID       `db:"id" json:"id"`
	OrderID   uuid.UUID       `db:"order_id" json:"order_id"`
	ProductID uuid.NullUUID   `db:"product_id" json:"product_id"`
	VariantID uuid.NullUUID   `db:"variant_id" json:"variant_id"`
	Sku       pgtype.Text     `db:"sku" json:"sku"`
	Name      string          `db:"name" json:"name"`
	Slug      pgtype.Text     `db:"slug" json:"slug"`
	ImagePath pgtype.Text     `db:"image_path" json:"image_path"`
	UnitPrice decimal.Decimal `db:"unit_price" json:"unit_price"`
	Quantity  int64           `db:"quantity" json:"quantity"`
	LineTotal decimal.Decimal `db:"line_total" json:"line_total"`
} //	@name	OrderItem

type OrderStatusHistory struct {
	ID         uuid.UUID        `db:"id" json:"id"`
	OrderID    uuid.UUID        `db:"order_id" json:"order_id"`
	FromStatus pgtype.Text      `db:"from_status" json:"from_status"`
	ToStatus   string           `db:"to_status" json:"to_status"`
	Actor      string           `db:"actor" json:"actor"`
	Comment    pgtype.Text      `db:"comment" json:"comment"`
	CreatedAt  pgtype.Timestamp `db:"created_at" json:"created_at"`
} //	@name	OrderStatusHistory

type PersonalAccessToken struct {
	ID            uuid.UUID        `db:"id" json:"id"`
	TokenableType string           `db:"tokenable_type" json:"tokenable_type"`
	TokenableID   uuid.UUID        `db:"tokenable_id" json:"tokenable_id"`
	Name          string           `db:"name" json:"name"`
	Token         string           `db:"token" json:"token"`
	LastUsedAt    pgtype.Timestamp `db:"last_used_at" json:"last_used_at"`
	ExpiresAt     *time.Time       `db:"expires_at" json:"expires_at"`
	CreatedAt     pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamp `db:"updated_at" json:"updated_at"`
} //	@name	PersonalAccessToken

type Product struct {
	ID             uuid.UUID            `db:"id" json:"id"`
	ExternalID     pgtype.Text          `db:"external_id" json:"external_id"`
	ManufacturerID uuid.NullUUID        `db:"manufacturer_id" json:"manufacturer_id"`
	Sku            pgtype.Text          `db:"sku" json:"sku"`
	Upc            pgtype.Text          `db:"upc" json:"upc"`
	Ean            pgtype.Text          `db:"ean" json:"ean"`
	Jan            pgtype.Text          `db:"jan" json:"jan"`
	Isbn           pgtype.Text          `db:"isbn" json:"isbn"`
	Mpn            pgtype.Text          `db:"mpn" json:"mpn"`
	Location       pgtype.Text          `db:"location" json:"location"`
	Quantity       int64                `db:"quantity" json:"quantity"`
	StockStatus    constant.StockStatus `db:"stock_status" json:"stock_status"`
	PriceRetail    decimal.Decimal      `db:"price_retail" json:"price_retail"`
	PriceBusiness  decimal.Decimal      `db:"price_business" json:"price_business"`
	PriceWholesale decimal.Decimal      `db:"price_wholesale" json:"price_wholesale"`
	Weight         decimal.Decimal      `db:"weight" json:"weight"`
	Length         decimal.Decimal      `db:"length" json:"length"`
	Width          decimal.Decimal      `db:"width" json:"width"`
	Height         decimal.Decimal      `db:"height" json:"height"`
	Subtract       bool                 `db:"subtract" json:"subtract"`
	Minimum        int64                `db:"minimum" json:"minimum"`
	Image          pgtype.Text          `db:"image" json:"image"`
	SortOrder      int32                `db:"sort_order" json:"sort_order"`
	IsEnable       bool                 `db:"is_enable" json:"is_enable"`
	CreatedAt      pgtype.Timestamp     `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamp     `db:"updated_at" json:"updated_at"`
} //	@name	Product

type ProductAttributeValue struct {
	ProductID        uuid.UUID        `db:"product_id" json:"product_id"`
	AttributeValueID uuid.UUID        `db:"attribute_value_id" json:"attribute_value_id"`
	CreatedAt        pgtype.Timestamp `db:"created_at" json:"created_at"`
} //	@name	ProductAttributeValue

type ProductMedium struct {
	ProductID uuid.UUID `db:"product_id" json:"product_id"`
	MediaID   uuid.UUID `db:"media_id" json:"media_id"`
	SortOrder int32     `db:"sort_order" json:"sort_order"`
} //	@name	ProductMedium

type ProductReview struct {
	ID        uuid.UUID        `db:"id" json:"id"`
	VariantID uuid.UUID        `db:"variant_id" json:"variant_id"`
	UserID    uuid.UUID        `db:"user_id" json:"user_id"`
	OrderID   uuid.NullUUID    `db:"order_id" json:"order_id"`
	Rating    int16            `db:"rating" json:"rating"`
	Title     pgtype.Text      `db:"title" json:"title"`
	Body      pgtype.Text      `db:"body" json:"body"`
	Status    string           `db:"status" json:"status"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	DeletedAt pgtype.Timestamp `db:"deleted_at" json:"deleted_at"`
} //	@name	ProductReview

type ProductVariant struct {
	ID              uuid.UUID        `db:"id" json:"id"`
	ProductID       uuid.UUID        `db:"product_id" json:"product_id"`
	CategoryID      uuid.NullUUID    `db:"category_id" json:"category_id"`
	Name            string           `db:"name" json:"name"`
	Slug            string           `db:"slug" json:"slug"`
	Description     pgtype.Text      `db:"description" json:"description"`
	Model           string           `db:"model" json:"model"`
	MetaTitle       pgtype.Text      `db:"meta_title" json:"meta_title"`
	MetaH1          pgtype.Text      `db:"meta_h1" json:"meta_h1"`
	MetaDescription pgtype.Text      `db:"meta_description" json:"meta_description"`
	MetaKeyword     pgtype.Text      `db:"meta_keyword" json:"meta_keyword"`
	SortOrder       int32            `db:"sort_order" json:"sort_order"`
	IsEnable        bool             `db:"is_enable" json:"is_enable"`
	Viewed          int64            `db:"viewed" json:"viewed"`
	CreatedAt       pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamp `db:"updated_at" json:"updated_at"`
} //	@name	ProductVariant

type ProductVariantCategory struct {
	ProductVariantID uuid.UUID        `db:"product_variant_id" json:"product_variant_id"`
	CategoryID       uuid.UUID        `db:"category_id" json:"category_id"`
	CreatedAt        pgtype.Timestamp `db:"created_at" json:"created_at"`
} //	@name	ProductVariantCategory

type RelatedProduct struct {
	VariantID        uuid.UUID `db:"variant_id" json:"variant_id"`
	RelatedVariantID uuid.UUID `db:"related_variant_id" json:"related_variant_id"`
} //	@name	RelatedProduct

type User struct {
	ID              uuid.UUID        `db:"id" json:"id"`
	Email           string           `db:"email" json:"email" validate:"required,email"`
	EmailVerifiedAt pgtype.Timestamp `db:"email_verified_at" json:"email_verified_at"`
	Password        pgtype.Text      `db:"password" json:"password"`
	RememberToken   pgtype.Text      `db:"remember_token" json:"remember_token"`
	Location        string           `db:"location" json:"location" validate:"omitempty,timezone"`
	Language        string           `db:"language" json:"language"`
	CreatedAt       pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	DeletedAt       pgtype.Timestamp `db:"deleted_at" json:"deleted_at"`
	IsAdmin         pgtype.Bool      `db:"is_admin" json:"is_admin"`
	Banned          pgtype.Bool      `db:"banned" json:"banned"`
} //	@name	User
