// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment_refunds.sql

package repository_payment_refunds

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
	"github.com/stickpro/go-store/internal/models"
)

const create = `-- name: Create :one
INSERT INTO payment_refunds (payment_id, amount, status, idempotency_key, reason, actor, created_at)
	VALUES ($1, $2, $3, $4, $5, $6, now())
	RETURNING id, payment_id, amount, status, idempotency_key, reason, actor, raw_response, created_at, updated_at
`

type CreateParams struct {
	PaymentID      uuid.UUID       `db:"payment_id" json:"payment_id"`
	Amount         decimal.Decimal `db:"amount" json:"amount"`
	Status         string          `db:"status" json:"status"`
	IdempotencyKey string          `db:"idempotency_key" json:"idempotency_key"`
	Reason         pgtype.Text     `db:"reason" json:"reason"`
	Actor          string          `db:"actor" json:"actor"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (*models.PaymentRefund, error) {
	row := q.db.QueryRow(ctx, create,
		arg.PaymentID,
		arg.Amount,
		arg.Status,
		arg.IdempotencyKey,
		arg.Reason,
		arg.Actor,
	)
	var i models.PaymentRefund
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.Amount,
		&i.Status,
		&i.IdempotencyKey,
		&i.Reason,
		&i.Actor,
		&i.RawResponse,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getByIdempotencyKey = `-- name: GetByIdempotencyKey :one
SELECT id, payment_id, amount, status, idempotency_key, reason, actor, raw_response, created_at, updated_at FROM payment_refunds WHERE idempotency_key = $1 LIMIT 1
`

func (q *Queries) GetByIdempotencyKey(ctx context.Context, idempotencyKey string) (*models.PaymentRefund, error) {
	row := q.db.QueryRow(ctx, getByIdempotencyKey, idempotencyKey)
	var i models.PaymentRefund
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.Amount,
		&i.Status,
		&i.IdempotencyKey,
		&i.Reason,
		&i.Actor,
		&i.RawResponse,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listByOrderID = `-- name: ListByOrderID :many
SELECT r.id, r.payment_id, r.amount, r.status, r.idempotency_key, r.reason, r.actor, r.raw_response, r.created_at, r.updated_at
FROM payment_refunds r
JOIN payments p ON p.id = r.payment_id
WHERE p.order_id = $1
ORDER BY r.created_at DESC
`

func (q *Queries) ListByOrderID(ctx context.Context, orderID uuid.UUID) ([]*models.PaymentRefund, error) {
	rows, err := q.db.Query(ctx, listByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*models.PaymentRefund{}
	for rows.Next() {
		var i models.PaymentRefund
		if err := rows.Scan(
			&i.ID,
			&i.PaymentID,
			&i.Amount,
			&i.Status,
			&i.IdempotencyKey,
			&i.Reason,
			&i.Actor,
			&i.RawResponse,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolvePending = `-- name: ResolvePending :one
UPDATE payment_refunds
SET status       = $2,
    raw_response = $3,
    updated_at   = now()
WHERE id = $1 AND status = 'pending'
RETURNING id, payment_id, amount, status, idempotency_key, reason, actor, raw_response, created_at, updated_at
`

type ResolvePendingParams struct {
	ID          uuid.UUID `db:"id" json:"id"`
	Status      string    `db:"status" json:"status"`
	RawResponse []byte    `db:"raw_response" json:"raw_response"`
}

// Settles a pending refund. Matches only a still-pending row, so a refund a
// webhook already settled is not resolved (or counted) a second time.
func (q *Queries) ResolvePending(ctx context.Context, arg ResolvePendingParams) (*models.PaymentRefund, error) {
	row := q.db.QueryRow(ctx, resolvePending, arg.ID, arg.Status, arg.RawResponse)
	var i models.PaymentRefund
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.Amount,
		&i.Status,
		&i.IdempotencyKey,
		&i.Reason,
		&i.Actor,
		&i.RawResponse,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const succeedAllPendingByPaymentID = `-- name: SucceedAllPendingByPaymentID :exec
UPDATE payment_refunds
SET status     = 'succeeded',
    updated_at = now()
WHERE payment_id = $1 AND status = 'pending'
`

// A full-refund webhook proves every refund still in flight went through.
func (q *Queries) SucceedAllPendingByPaymentID(ctx context.Context, paymentID uuid.UUID) error {
	_, err := q.db.Exec(ctx, succeedAllPendingByPaymentID, paymentID)
	return err
}

const sumPendingByOrderID = `-- name: SumPendingByOrderID :one
SELECT coalesce(sum(r.amount), 0)::numeric AS total
FROM payment_refunds r
JOIN payments p ON p.id = r.payment_id
WHERE p.order_id = $1 AND r.status = 'pending'
`

// Refunds still in flight across all of an order's payments.
func (q *Queries) SumPendingByOrderID(ctx context.Context, orderID uuid.UUID) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, sumPendingByOrderID, orderID)
	var total decimal.Decimal
	err := row.Scan(&total)
	return total, err
}

const sumPendingByPaymentID = `-- name: SumPendingByPaymentID :one
SELECT coalesce(sum(amount), 0)::numeric AS total
FROM payment_refunds
WHERE payment_id = $1 AND status = 'pending'
`

// Refunds sent to the provider whose outcome isn't known yet. They count
// against the payment's remaining balance until resolved.
func (q *Queries) SumPendingByPaymentID(ctx context.Context, paymentID uuid.UUID) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, sumPendingByPaymentID, paymentID)
	var total decimal.Decimal
	err := row.Scan(&total)
	return total, err
}
