// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository_payment_refunds

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
	"github.com/stickpro/go-store/internal/models"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) (*models.PaymentRefund, error)
	GetByIdempotencyKey(ctx context.Context, idempotencyKey string) (*models.PaymentRefund, error)
	ListByOrderID(ctx context.Context, orderID uuid.UUID) ([]*models.PaymentRefund, error)
	// Settles a pending refund. Matches only a still-pending row, so a refund a
	// webhook already settled is not resolved (or counted) a second time.
	ResolvePending(ctx context.Context, arg ResolvePendingParams) (*models.PaymentRefund, error)
	// A full-refund webhook proves every refund still in flight went through.
	SucceedAllPendingByPaymentID(ctx context.Context, paymentID uuid.UUID) error
	// Refunds still in flight across all of an order's payments.
	SumPendingByOrderID(ctx context.Context, orderID uuid.UUID) (decimal.Decimal, error)
	// Refunds sent to the provider whose outcome isn't known yet. They count
	// against the payment's remaining balance until resolved.
	SumPendingByPaymentID(ctx context.Context, paymentID uuid.UUID) (decimal.Decimal, error)
}

var _ Querier = (*Queries)(nil)
