// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product_variants.sql

package repository_product_variants

import (
	"context"

	"github.com/google/uuid"
	"github.com/stickpro/go-store/internal/models"
)

const getByProductID = `-- name: GetByProductID :many
SELECT id, product_id, category_id, name, slug, description, meta_title, meta_h1, meta_description, meta_keyword, image, sort_order, is_enable, viewed, created_at, updated_at FROM product_variants WHERE product_id = $1 ORDER BY sort_order ASC
`

func (q *Queries) GetByProductID(ctx context.Context, productID uuid.UUID) ([]*models.ProductVariant, error) {
	rows, err := q.db.Query(ctx, getByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*models.ProductVariant{}
	for rows.Next() {
		var i models.ProductVariant
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.CategoryID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.MetaTitle,
			&i.MetaH1,
			&i.MetaDescription,
			&i.MetaKeyword,
			&i.Image,
			&i.SortOrder,
			&i.IsEnable,
			&i.Viewed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBySlug = `-- name: GetBySlug :one
SELECT id, product_id, category_id, name, slug, description, meta_title, meta_h1, meta_description, meta_keyword, image, sort_order, is_enable, viewed, created_at, updated_at FROM product_variants WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetBySlug(ctx context.Context, slug string) (*models.ProductVariant, error) {
	row := q.db.QueryRow(ctx, getBySlug, slug)
	var i models.ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.MetaTitle,
		&i.MetaH1,
		&i.MetaDescription,
		&i.MetaKeyword,
		&i.Image,
		&i.SortOrder,
		&i.IsEnable,
		&i.Viewed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
