// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: product_variants.sql

package repository_product_variants

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/stickpro/go-store/internal/models"
)

const getByProductID = `-- name: GetByProductID :many
SELECT id, product_id, category_id, name, slug, description, model, meta_title, meta_h1, meta_description, meta_keyword, sort_order, is_enable, viewed, created_at, updated_at FROM product_variants WHERE product_id = $1 ORDER BY sort_order ASC
`

func (q *Queries) GetByProductID(ctx context.Context, productID uuid.UUID) ([]*models.ProductVariant, error) {
	rows, err := q.db.Query(ctx, getByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*models.ProductVariant{}
	for rows.Next() {
		var i models.ProductVariant
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.CategoryID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Model,
			&i.MetaTitle,
			&i.MetaH1,
			&i.MetaDescription,
			&i.MetaKeyword,
			&i.SortOrder,
			&i.IsEnable,
			&i.Viewed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBySlug = `-- name: GetBySlug :one
SELECT id, product_id, category_id, name, slug, description, model, meta_title, meta_h1, meta_description, meta_keyword, sort_order, is_enable, viewed, created_at, updated_at FROM product_variants WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetBySlug(ctx context.Context, slug string) (*models.ProductVariant, error) {
	row := q.db.QueryRow(ctx, getBySlug, slug)
	var i models.ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Model,
		&i.MetaTitle,
		&i.MetaH1,
		&i.MetaDescription,
		&i.MetaKeyword,
		&i.SortOrder,
		&i.IsEnable,
		&i.Viewed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const sitemapProducts = `-- name: SitemapProducts :many
SELECT pv.slug, pv.updated_at
FROM product_variants pv
JOIN products p ON p.id = pv.product_id
WHERE pv.is_enable AND p.is_enable
ORDER BY pv.updated_at DESC NULLS LAST
`

type SitemapProductsRow struct {
	Slug      string           `db:"slug" json:"slug"`
	UpdatedAt pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

// Enabled product-variant pages for the sitemap feed. Both the variant and its
// parent product must be enabled; updated_at is the variant's own last change.
func (q *Queries) SitemapProducts(ctx context.Context) ([]*SitemapProductsRow, error) {
	rows, err := q.db.Query(ctx, sitemapProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*SitemapProductsRow{}
	for rows.Next() {
		var i SitemapProductsRow
		if err := rows.Scan(&i.Slug, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
