// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product_variants_gen.sql

package repository_product_variants

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/stickpro/go-store/internal/models"
)

const create = `-- name: Create :one
INSERT INTO product_variants (product_id, category_id, name, slug, description, meta_title, meta_h1, meta_description, meta_keyword, image, sort_order, is_enable, viewed, created_at)
	VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, now())
	RETURNING id, product_id, category_id, name, slug, description, meta_title, meta_h1, meta_description, meta_keyword, image, sort_order, is_enable, viewed, created_at, updated_at
`

type CreateParams struct {
	ProductID       uuid.UUID     `db:"product_id" json:"product_id"`
	CategoryID      uuid.NullUUID `db:"category_id" json:"category_id"`
	Name            string        `db:"name" json:"name"`
	Slug            string        `db:"slug" json:"slug"`
	Description     pgtype.Text   `db:"description" json:"description"`
	MetaTitle       pgtype.Text   `db:"meta_title" json:"meta_title"`
	MetaH1          pgtype.Text   `db:"meta_h1" json:"meta_h1"`
	MetaDescription pgtype.Text   `db:"meta_description" json:"meta_description"`
	MetaKeyword     pgtype.Text   `db:"meta_keyword" json:"meta_keyword"`
	Image           pgtype.Text   `db:"image" json:"image"`
	SortOrder       int32         `db:"sort_order" json:"sort_order"`
	IsEnable        bool          `db:"is_enable" json:"is_enable"`
	Viewed          int64         `db:"viewed" json:"viewed"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (*models.ProductVariant, error) {
	row := q.db.QueryRow(ctx, create,
		arg.ProductID,
		arg.CategoryID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.MetaTitle,
		arg.MetaH1,
		arg.MetaDescription,
		arg.MetaKeyword,
		arg.Image,
		arg.SortOrder,
		arg.IsEnable,
		arg.Viewed,
	)
	var i models.ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.MetaTitle,
		&i.MetaH1,
		&i.MetaDescription,
		&i.MetaKeyword,
		&i.Image,
		&i.SortOrder,
		&i.IsEnable,
		&i.Viewed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const delete = `-- name: Delete :exec
DELETE FROM product_variants WHERE id=$1
`

func (q *Queries) Delete(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, delete, id)
	return err
}

const get = `-- name: Get :one
SELECT id, product_id, category_id, name, slug, description, meta_title, meta_h1, meta_description, meta_keyword, image, sort_order, is_enable, viewed, created_at, updated_at FROM product_variants WHERE id=$1 LIMIT 1
`

func (q *Queries) Get(ctx context.Context, id uuid.UUID) (*models.ProductVariant, error) {
	row := q.db.QueryRow(ctx, get, id)
	var i models.ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.MetaTitle,
		&i.MetaH1,
		&i.MetaDescription,
		&i.MetaKeyword,
		&i.Image,
		&i.SortOrder,
		&i.IsEnable,
		&i.Viewed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getAll = `-- name: GetAll :many
SELECT id, product_id, category_id, name, slug, description, meta_title, meta_h1, meta_description, meta_keyword, image, sort_order, is_enable, viewed, created_at, updated_at FROM product_variants LIMIT $1 OFFSET $2
`

type GetAllParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) GetAll(ctx context.Context, arg GetAllParams) ([]*models.ProductVariant, error) {
	rows, err := q.db.Query(ctx, getAll, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*models.ProductVariant{}
	for rows.Next() {
		var i models.ProductVariant
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.CategoryID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.MetaTitle,
			&i.MetaH1,
			&i.MetaDescription,
			&i.MetaKeyword,
			&i.Image,
			&i.SortOrder,
			&i.IsEnable,
			&i.Viewed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const update = `-- name: Update :one
UPDATE product_variants
	SET product_id=$1, category_id=$2, name=$3, slug=$4, description=$5, meta_title=$6, 
		meta_h1=$7, meta_description=$8, meta_keyword=$9, image=$10, sort_order=$11, is_enable=$12, 
		viewed=$13, updated_at=now()
	WHERE id=$14
	RETURNING id, product_id, category_id, name, slug, description, meta_title, meta_h1, meta_description, meta_keyword, image, sort_order, is_enable, viewed, created_at, updated_at
`

type UpdateParams struct {
	ProductID       uuid.UUID     `db:"product_id" json:"product_id"`
	CategoryID      uuid.NullUUID `db:"category_id" json:"category_id"`
	Name            string        `db:"name" json:"name"`
	Slug            string        `db:"slug" json:"slug"`
	Description     pgtype.Text   `db:"description" json:"description"`
	MetaTitle       pgtype.Text   `db:"meta_title" json:"meta_title"`
	MetaH1          pgtype.Text   `db:"meta_h1" json:"meta_h1"`
	MetaDescription pgtype.Text   `db:"meta_description" json:"meta_description"`
	MetaKeyword     pgtype.Text   `db:"meta_keyword" json:"meta_keyword"`
	Image           pgtype.Text   `db:"image" json:"image"`
	SortOrder       int32         `db:"sort_order" json:"sort_order"`
	IsEnable        bool          `db:"is_enable" json:"is_enable"`
	Viewed          int64         `db:"viewed" json:"viewed"`
	ID              uuid.UUID     `db:"id" json:"id"`
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) (*models.ProductVariant, error) {
	row := q.db.QueryRow(ctx, update,
		arg.ProductID,
		arg.CategoryID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.MetaTitle,
		arg.MetaH1,
		arg.MetaDescription,
		arg.MetaKeyword,
		arg.Image,
		arg.SortOrder,
		arg.IsEnable,
		arg.Viewed,
		arg.ID,
	)
	var i models.ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.MetaTitle,
		&i.MetaH1,
		&i.MetaDescription,
		&i.MetaKeyword,
		&i.Image,
		&i.SortOrder,
		&i.IsEnable,
		&i.Viewed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
