// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository_product_variants

import (
	"context"

	"github.com/google/uuid"
	"github.com/stickpro/go-store/internal/models"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) (*models.ProductVariant, error)
	Delete(ctx context.Context, id uuid.UUID) error
	Get(ctx context.Context, id uuid.UUID) (*models.ProductVariant, error)
	GetAll(ctx context.Context, arg GetAllParams) ([]*models.ProductVariant, error)
	GetByProductID(ctx context.Context, productID uuid.UUID) ([]*models.ProductVariant, error)
	GetBySlug(ctx context.Context, slug string) (*models.ProductVariant, error)
	Update(ctx context.Context, arg UpdateParams) (*models.ProductVariant, error)
}

var _ Querier = (*Queries)(nil)
