// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository_personal_access_tokens

import (
	"context"

	"github.com/stickpro/go-store/internal/models"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) (*models.PersonalAccessToken, error)
	GetByToken(ctx context.Context, token string) (*models.PersonalAccessToken, error)
}

var _ Querier = (*Queries)(nil)
