// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: order_edits.sql

package repository_order_edits

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
	"github.com/stickpro/go-store/internal/models"
)

const create = `-- name: Create :one
INSERT INTO order_edits (order_id, actor, comment, lines_before, lines_after, grand_total_before, grand_total_after, created_at)
	VALUES ($1, $2, $3, $4, $5, $6, $7, now())
	RETURNING id, order_id, actor, comment, lines_before, lines_after, grand_total_before, grand_total_after, created_at
`

type CreateParams struct {
	OrderID          uuid.UUID       `db:"order_id" json:"order_id"`
	Actor            string          `db:"actor" json:"actor"`
	Comment          pgtype.Text     `db:"comment" json:"comment"`
	LinesBefore      []byte          `db:"lines_before" json:"lines_before"`
	LinesAfter       []byte          `db:"lines_after" json:"lines_after"`
	GrandTotalBefore decimal.Decimal `db:"grand_total_before" json:"grand_total_before"`
	GrandTotalAfter  decimal.Decimal `db:"grand_total_after" json:"grand_total_after"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (*models.OrderEdit, error) {
	row := q.db.QueryRow(ctx, create,
		arg.OrderID,
		arg.Actor,
		arg.Comment,
		arg.LinesBefore,
		arg.LinesAfter,
		arg.GrandTotalBefore,
		arg.GrandTotalAfter,
	)
	var i models.OrderEdit
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Actor,
		&i.Comment,
		&i.LinesBefore,
		&i.LinesAfter,
		&i.GrandTotalBefore,
		&i.GrandTotalAfter,
		&i.CreatedAt,
	)
	return &i, err
}

const listByOrderID = `-- name: ListByOrderID :many
SELECT id, order_id, actor, comment, lines_before, lines_after, grand_total_before, grand_total_after, created_at FROM order_edits WHERE order_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListByOrderID(ctx context.Context, orderID uuid.UUID) ([]*models.OrderEdit, error) {
	rows, err := q.db.Query(ctx, listByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*models.OrderEdit{}
	for rows.Next() {
		var i models.OrderEdit
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.Actor,
			&i.Comment,
			&i.LinesBefore,
			&i.LinesAfter,
			&i.GrandTotalBefore,
			&i.GrandTotalAfter,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
