// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories_gen.sql

package repository_categories

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/stickpro/go-store/internal/models"
)

const create = `-- name: Create :one
INSERT INTO categories (parent_id, name, slug, description, image_path, meta_title, meta_h1, meta_description, meta_keyword, is_enable, created_at)
	VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, now())
	RETURNING id, parent_id, name, slug, description, image_path, meta_title, meta_h1, meta_description, meta_keyword, is_enable, created_at, updated_at
`

type CreateParams struct {
	ParentID        uuid.NullUUID `db:"parent_id" json:"parent_id"`
	Name            string        `db:"name" json:"name"`
	Slug            string        `db:"slug" json:"slug"`
	Description     pgtype.Text   `db:"description" json:"description"`
	ImagePath       pgtype.Text   `db:"image_path" json:"image_path"`
	MetaTitle       pgtype.Text   `db:"meta_title" json:"meta_title"`
	MetaH1          pgtype.Text   `db:"meta_h1" json:"meta_h1"`
	MetaDescription pgtype.Text   `db:"meta_description" json:"meta_description"`
	MetaKeyword     pgtype.Text   `db:"meta_keyword" json:"meta_keyword"`
	IsEnable        bool          `db:"is_enable" json:"is_enable"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (*models.Category, error) {
	row := q.db.QueryRow(ctx, create,
		arg.ParentID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.ImagePath,
		arg.MetaTitle,
		arg.MetaH1,
		arg.MetaDescription,
		arg.MetaKeyword,
		arg.IsEnable,
	)
	var i models.Category
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.ImagePath,
		&i.MetaTitle,
		&i.MetaH1,
		&i.MetaDescription,
		&i.MetaKeyword,
		&i.IsEnable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const update = `-- name: Update :one
UPDATE categories
	SET parent_id=$1, name=$2, slug=$3, description=$4, image_path=$5, meta_title=$6, 
		meta_h1=$7, meta_description=$8, meta_keyword=$9, is_enable=$10, updated_at=now()
	WHERE id=$11
	RETURNING id, parent_id, name, slug, description, image_path, meta_title, meta_h1, meta_description, meta_keyword, is_enable, created_at, updated_at
`

type UpdateParams struct {
	ParentID        uuid.NullUUID `db:"parent_id" json:"parent_id"`
	Name            string        `db:"name" json:"name"`
	Slug            string        `db:"slug" json:"slug"`
	Description     pgtype.Text   `db:"description" json:"description"`
	ImagePath       pgtype.Text   `db:"image_path" json:"image_path"`
	MetaTitle       pgtype.Text   `db:"meta_title" json:"meta_title"`
	MetaH1          pgtype.Text   `db:"meta_h1" json:"meta_h1"`
	MetaDescription pgtype.Text   `db:"meta_description" json:"meta_description"`
	MetaKeyword     pgtype.Text   `db:"meta_keyword" json:"meta_keyword"`
	IsEnable        bool          `db:"is_enable" json:"is_enable"`
	ID              uuid.UUID     `db:"id" json:"id"`
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) (*models.Category, error) {
	row := q.db.QueryRow(ctx, update,
		arg.ParentID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.ImagePath,
		arg.MetaTitle,
		arg.MetaH1,
		arg.MetaDescription,
		arg.MetaKeyword,
		arg.IsEnable,
		arg.ID,
	)
	var i models.Category
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.ImagePath,
		&i.MetaTitle,
		&i.MetaH1,
		&i.MetaDescription,
		&i.MetaKeyword,
		&i.IsEnable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
