// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products_gen.sql

package repository_products

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
	"github.com/stickpro/go-store/internal/constant"
	"github.com/stickpro/go-store/internal/models"
)

const create = `-- name: Create :one
INSERT INTO products (external_id, manufacturer_id, model, sku, upc, ean, jan, isbn, mpn, location, quantity, stock_status, price, weight, length, width, height, subtract, minimum, sort_order, is_enable, created_at)
	VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, now())
	RETURNING id, external_id, manufacturer_id, model, sku, upc, ean, jan, isbn, mpn, location, quantity, stock_status, price, weight, length, width, height, subtract, minimum, sort_order, is_enable, created_at, updated_at
`

type CreateParams struct {
	ExternalID     pgtype.Text          `db:"external_id" json:"external_id"`
	ManufacturerID uuid.NullUUID        `db:"manufacturer_id" json:"manufacturer_id"`
	Model          string               `db:"model" json:"model"`
	Sku            pgtype.Text          `db:"sku" json:"sku"`
	Upc            pgtype.Text          `db:"upc" json:"upc"`
	Ean            pgtype.Text          `db:"ean" json:"ean"`
	Jan            pgtype.Text          `db:"jan" json:"jan"`
	Isbn           pgtype.Text          `db:"isbn" json:"isbn"`
	Mpn            pgtype.Text          `db:"mpn" json:"mpn"`
	Location       pgtype.Text          `db:"location" json:"location"`
	Quantity       int64                `db:"quantity" json:"quantity"`
	StockStatus    constant.StockStatus `db:"stock_status" json:"stock_status"`
	Price          decimal.Decimal      `db:"price" json:"price"`
	Weight         decimal.Decimal      `db:"weight" json:"weight"`
	Length         decimal.Decimal      `db:"length" json:"length"`
	Width          decimal.Decimal      `db:"width" json:"width"`
	Height         decimal.Decimal      `db:"height" json:"height"`
	Subtract       bool                 `db:"subtract" json:"subtract"`
	Minimum        int64                `db:"minimum" json:"minimum"`
	SortOrder      int32                `db:"sort_order" json:"sort_order"`
	IsEnable       bool                 `db:"is_enable" json:"is_enable"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (*models.Product, error) {
	row := q.db.QueryRow(ctx, create,
		arg.ExternalID,
		arg.ManufacturerID,
		arg.Model,
		arg.Sku,
		arg.Upc,
		arg.Ean,
		arg.Jan,
		arg.Isbn,
		arg.Mpn,
		arg.Location,
		arg.Quantity,
		arg.StockStatus,
		arg.Price,
		arg.Weight,
		arg.Length,
		arg.Width,
		arg.Height,
		arg.Subtract,
		arg.Minimum,
		arg.SortOrder,
		arg.IsEnable,
	)
	var i models.Product
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.ManufacturerID,
		&i.Model,
		&i.Sku,
		&i.Upc,
		&i.Ean,
		&i.Jan,
		&i.Isbn,
		&i.Mpn,
		&i.Location,
		&i.Quantity,
		&i.StockStatus,
		&i.Price,
		&i.Weight,
		&i.Length,
		&i.Width,
		&i.Height,
		&i.Subtract,
		&i.Minimum,
		&i.SortOrder,
		&i.IsEnable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const update = `-- name: Update :one
UPDATE products
	SET external_id=$1, manufacturer_id=$2, model=$3, sku=$4, upc=$5, ean=$6, 
		jan=$7, isbn=$8, mpn=$9, location=$10, quantity=$11, stock_status=$12, 
		price=$13, weight=$14, length=$15, width=$16, height=$17, subtract=$18, 
		minimum=$19, sort_order=$20, is_enable=$21, updated_at=now()
	WHERE id=$22
	RETURNING id, external_id, manufacturer_id, model, sku, upc, ean, jan, isbn, mpn, location, quantity, stock_status, price, weight, length, width, height, subtract, minimum, sort_order, is_enable, created_at, updated_at
`

type UpdateParams struct {
	ExternalID     pgtype.Text          `db:"external_id" json:"external_id"`
	ManufacturerID uuid.NullUUID        `db:"manufacturer_id" json:"manufacturer_id"`
	Model          string               `db:"model" json:"model"`
	Sku            pgtype.Text          `db:"sku" json:"sku"`
	Upc            pgtype.Text          `db:"upc" json:"upc"`
	Ean            pgtype.Text          `db:"ean" json:"ean"`
	Jan            pgtype.Text          `db:"jan" json:"jan"`
	Isbn           pgtype.Text          `db:"isbn" json:"isbn"`
	Mpn            pgtype.Text          `db:"mpn" json:"mpn"`
	Location       pgtype.Text          `db:"location" json:"location"`
	Quantity       int64                `db:"quantity" json:"quantity"`
	StockStatus    constant.StockStatus `db:"stock_status" json:"stock_status"`
	Price          decimal.Decimal      `db:"price" json:"price"`
	Weight         decimal.Decimal      `db:"weight" json:"weight"`
	Length         decimal.Decimal      `db:"length" json:"length"`
	Width          decimal.Decimal      `db:"width" json:"width"`
	Height         decimal.Decimal      `db:"height" json:"height"`
	Subtract       bool                 `db:"subtract" json:"subtract"`
	Minimum        int64                `db:"minimum" json:"minimum"`
	SortOrder      int32                `db:"sort_order" json:"sort_order"`
	IsEnable       bool                 `db:"is_enable" json:"is_enable"`
	ID             uuid.UUID            `db:"id" json:"id"`
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) (*models.Product, error) {
	row := q.db.QueryRow(ctx, update,
		arg.ExternalID,
		arg.ManufacturerID,
		arg.Model,
		arg.Sku,
		arg.Upc,
		arg.Ean,
		arg.Jan,
		arg.Isbn,
		arg.Mpn,
		arg.Location,
		arg.Quantity,
		arg.StockStatus,
		arg.Price,
		arg.Weight,
		arg.Length,
		arg.Width,
		arg.Height,
		arg.Subtract,
		arg.Minimum,
		arg.SortOrder,
		arg.IsEnable,
		arg.ID,
	)
	var i models.Product
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.ManufacturerID,
		&i.Model,
		&i.Sku,
		&i.Upc,
		&i.Ean,
		&i.Jan,
		&i.Isbn,
		&i.Mpn,
		&i.Location,
		&i.Quantity,
		&i.StockStatus,
		&i.Price,
		&i.Weight,
		&i.Length,
		&i.Width,
		&i.Height,
		&i.Subtract,
		&i.Minimum,
		&i.SortOrder,
		&i.IsEnable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
