// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products_gen.sql

package repository_products

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
	"github.com/stickpro/go-store/internal/constant"
	"github.com/stickpro/go-store/internal/models"
)

const create = `-- name: Create :one
INSERT INTO products (external_id, manufacturer_id, sku, upc, ean, jan, isbn, mpn, location, quantity, stock_status, price_retail, price_business, price_wholesale, weight, length, width, height, subtract, minimum, image, sort_order, is_enable, created_at)
	VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, now())
	RETURNING id, external_id, manufacturer_id, sku, upc, ean, jan, isbn, mpn, location, quantity, stock_status, price_retail, price_business, price_wholesale, weight, length, width, height, subtract, minimum, image, sort_order, is_enable, created_at, updated_at
`

type CreateParams struct {
	ExternalID     pgtype.Text          `db:"external_id" json:"external_id"`
	ManufacturerID uuid.NullUUID        `db:"manufacturer_id" json:"manufacturer_id"`
	Sku            pgtype.Text          `db:"sku" json:"sku"`
	Upc            pgtype.Text          `db:"upc" json:"upc"`
	Ean            pgtype.Text          `db:"ean" json:"ean"`
	Jan            pgtype.Text          `db:"jan" json:"jan"`
	Isbn           pgtype.Text          `db:"isbn" json:"isbn"`
	Mpn            pgtype.Text          `db:"mpn" json:"mpn"`
	Location       pgtype.Text          `db:"location" json:"location"`
	Quantity       int64                `db:"quantity" json:"quantity"`
	StockStatus    constant.StockStatus `db:"stock_status" json:"stock_status"`
	PriceRetail    decimal.Decimal      `db:"price_retail" json:"price_retail"`
	PriceBusiness  decimal.Decimal      `db:"price_business" json:"price_business"`
	PriceWholesale decimal.Decimal      `db:"price_wholesale" json:"price_wholesale"`
	Weight         decimal.Decimal      `db:"weight" json:"weight"`
	Length         decimal.Decimal      `db:"length" json:"length"`
	Width          decimal.Decimal      `db:"width" json:"width"`
	Height         decimal.Decimal      `db:"height" json:"height"`
	Subtract       bool                 `db:"subtract" json:"subtract"`
	Minimum        int64                `db:"minimum" json:"minimum"`
	Image          pgtype.Text          `db:"image" json:"image"`
	SortOrder      int32                `db:"sort_order" json:"sort_order"`
	IsEnable       bool                 `db:"is_enable" json:"is_enable"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (*models.Product, error) {
	row := q.db.QueryRow(ctx, create,
		arg.ExternalID,
		arg.ManufacturerID,
		arg.Sku,
		arg.Upc,
		arg.Ean,
		arg.Jan,
		arg.Isbn,
		arg.Mpn,
		arg.Location,
		arg.Quantity,
		arg.StockStatus,
		arg.PriceRetail,
		arg.PriceBusiness,
		arg.PriceWholesale,
		arg.Weight,
		arg.Length,
		arg.Width,
		arg.Height,
		arg.Subtract,
		arg.Minimum,
		arg.Image,
		arg.SortOrder,
		arg.IsEnable,
	)
	var i models.Product
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.ManufacturerID,
		&i.Sku,
		&i.Upc,
		&i.Ean,
		&i.Jan,
		&i.Isbn,
		&i.Mpn,
		&i.Location,
		&i.Quantity,
		&i.StockStatus,
		&i.PriceRetail,
		&i.PriceBusiness,
		&i.PriceWholesale,
		&i.Weight,
		&i.Length,
		&i.Width,
		&i.Height,
		&i.Subtract,
		&i.Minimum,
		&i.Image,
		&i.SortOrder,
		&i.IsEnable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const update = `-- name: Update :one
UPDATE products
	SET external_id=$1, manufacturer_id=$2, sku=$3, upc=$4, ean=$5, jan=$6, 
		isbn=$7, mpn=$8, location=$9, quantity=$10, stock_status=$11, price_retail=$12, 
		price_business=$13, price_wholesale=$14, weight=$15, length=$16, width=$17, height=$18, 
		subtract=$19, minimum=$20, image=$21, sort_order=$22, is_enable=$23, updated_at=now()
	WHERE id=$24
	RETURNING id, external_id, manufacturer_id, sku, upc, ean, jan, isbn, mpn, location, quantity, stock_status, price_retail, price_business, price_wholesale, weight, length, width, height, subtract, minimum, image, sort_order, is_enable, created_at, updated_at
`

type UpdateParams struct {
	ExternalID     pgtype.Text          `db:"external_id" json:"external_id"`
	ManufacturerID uuid.NullUUID        `db:"manufacturer_id" json:"manufacturer_id"`
	Sku            pgtype.Text          `db:"sku" json:"sku"`
	Upc            pgtype.Text          `db:"upc" json:"upc"`
	Ean            pgtype.Text          `db:"ean" json:"ean"`
	Jan            pgtype.Text          `db:"jan" json:"jan"`
	Isbn           pgtype.Text          `db:"isbn" json:"isbn"`
	Mpn            pgtype.Text          `db:"mpn" json:"mpn"`
	Location       pgtype.Text          `db:"location" json:"location"`
	Quantity       int64                `db:"quantity" json:"quantity"`
	StockStatus    constant.StockStatus `db:"stock_status" json:"stock_status"`
	PriceRetail    decimal.Decimal      `db:"price_retail" json:"price_retail"`
	PriceBusiness  decimal.Decimal      `db:"price_business" json:"price_business"`
	PriceWholesale decimal.Decimal      `db:"price_wholesale" json:"price_wholesale"`
	Weight         decimal.Decimal      `db:"weight" json:"weight"`
	Length         decimal.Decimal      `db:"length" json:"length"`
	Width          decimal.Decimal      `db:"width" json:"width"`
	Height         decimal.Decimal      `db:"height" json:"height"`
	Subtract       bool                 `db:"subtract" json:"subtract"`
	Minimum        int64                `db:"minimum" json:"minimum"`
	Image          pgtype.Text          `db:"image" json:"image"`
	SortOrder      int32                `db:"sort_order" json:"sort_order"`
	IsEnable       bool                 `db:"is_enable" json:"is_enable"`
	ID             uuid.UUID            `db:"id" json:"id"`
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) (*models.Product, error) {
	row := q.db.QueryRow(ctx, update,
		arg.ExternalID,
		arg.ManufacturerID,
		arg.Sku,
		arg.Upc,
		arg.Ean,
		arg.Jan,
		arg.Isbn,
		arg.Mpn,
		arg.Location,
		arg.Quantity,
		arg.StockStatus,
		arg.PriceRetail,
		arg.PriceBusiness,
		arg.PriceWholesale,
		arg.Weight,
		arg.Length,
		arg.Width,
		arg.Height,
		arg.Subtract,
		arg.Minimum,
		arg.Image,
		arg.SortOrder,
		arg.IsEnable,
		arg.ID,
	)
	var i models.Product
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.ManufacturerID,
		&i.Sku,
		&i.Upc,
		&i.Ean,
		&i.Jan,
		&i.Isbn,
		&i.Mpn,
		&i.Location,
		&i.Quantity,
		&i.StockStatus,
		&i.PriceRetail,
		&i.PriceBusiness,
		&i.PriceWholesale,
		&i.Weight,
		&i.Length,
		&i.Width,
		&i.Height,
		&i.Subtract,
		&i.Minimum,
		&i.Image,
		&i.SortOrder,
		&i.IsEnable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
