// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package repository_products

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
	"github.com/stickpro/go-store/internal/models"
)

const getByExternalID = `-- name: GetByExternalID :one
SELECT id, external_id, manufacturer_id, model, sku, upc, ean, jan, isbn, mpn, location, quantity, stock_status, price, weight, length, width, height, subtract, minimum, sort_order, is_enable, created_at, updated_at FROM products WHERE external_id = $1 LIMIT 1
`

func (q *Queries) GetByExternalID(ctx context.Context, externalID pgtype.Text) (*models.Product, error) {
	row := q.db.QueryRow(ctx, getByExternalID, externalID)
	var i models.Product
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.ManufacturerID,
		&i.Model,
		&i.Sku,
		&i.Upc,
		&i.Ean,
		&i.Jan,
		&i.Isbn,
		&i.Mpn,
		&i.Location,
		&i.Quantity,
		&i.StockStatus,
		&i.Price,
		&i.Weight,
		&i.Length,
		&i.Width,
		&i.Height,
		&i.Subtract,
		&i.Minimum,
		&i.SortOrder,
		&i.IsEnable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getByID = `-- name: GetByID :one
SELECT id, external_id, manufacturer_id, model, sku, upc, ean, jan, isbn, mpn, location, quantity, stock_status, price, weight, length, width, height, subtract, minimum, sort_order, is_enable, created_at, updated_at FROM products WHERE id = $1 LIMIT 1
`

func (q *Queries) GetByID(ctx context.Context, id uuid.UUID) (*models.Product, error) {
	row := q.db.QueryRow(ctx, getByID, id)
	var i models.Product
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.ManufacturerID,
		&i.Model,
		&i.Sku,
		&i.Upc,
		&i.Ean,
		&i.Jan,
		&i.Isbn,
		&i.Mpn,
		&i.Location,
		&i.Quantity,
		&i.StockStatus,
		&i.Price,
		&i.Weight,
		&i.Length,
		&i.Width,
		&i.Height,
		&i.Subtract,
		&i.Minimum,
		&i.SortOrder,
		&i.IsEnable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getBySlug = `-- name: GetBySlug :one
SELECT p.id, p.external_id, p.manufacturer_id, p.model, p.sku, p.upc, p.ean, p.jan, p.isbn, p.mpn, p.location, p.quantity, p.stock_status, p.price, p.weight, p.length, p.width, p.height, p.subtract, p.minimum, p.sort_order, p.is_enable, p.created_at, p.updated_at FROM products p
INNER JOIN product_variants pv ON pv.product_id = p.id
WHERE pv.slug = $1 LIMIT 1
`

func (q *Queries) GetBySlug(ctx context.Context, slug string) (*models.Product, error) {
	row := q.db.QueryRow(ctx, getBySlug, slug)
	var i models.Product
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.ManufacturerID,
		&i.Model,
		&i.Sku,
		&i.Upc,
		&i.Ean,
		&i.Jan,
		&i.Isbn,
		&i.Mpn,
		&i.Location,
		&i.Quantity,
		&i.StockStatus,
		&i.Price,
		&i.Weight,
		&i.Length,
		&i.Width,
		&i.Height,
		&i.Subtract,
		&i.Minimum,
		&i.SortOrder,
		&i.IsEnable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getCartItemsByVariantIDs = `-- name: GetCartItemsByVariantIDs :many
SELECT p.id       AS product_id,
       p.price,
       p.quantity  AS max_quantity,
       p.is_enable AS product_enabled,
       pv.id       AS variant_id,
       pv.name,
       pv.slug,
       pv.image,
       pv.is_enable AS variant_enabled
FROM products p
         JOIN product_variants pv ON pv.product_id = p.id
WHERE pv.id = ANY ($1::uuid[])
`

type GetCartItemsByVariantIDsRow struct {
	ProductID      uuid.UUID       `db:"product_id" json:"product_id"`
	Price          decimal.Decimal `db:"price" json:"price"`
	MaxQuantity    int64           `db:"max_quantity" json:"max_quantity"`
	ProductEnabled bool            `db:"product_enabled" json:"product_enabled"`
	VariantID      uuid.UUID       `db:"variant_id" json:"variant_id"`
	Name           string          `db:"name" json:"name"`
	Slug           string          `db:"slug" json:"slug"`
	Image          pgtype.Text     `db:"image" json:"image"`
	VariantEnabled bool            `db:"variant_enabled" json:"variant_enabled"`
}

func (q *Queries) GetCartItemsByVariantIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]*GetCartItemsByVariantIDsRow, error) {
	rows, err := q.db.Query(ctx, getCartItemsByVariantIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetCartItemsByVariantIDsRow{}
	for rows.Next() {
		var i GetCartItemsByVariantIDsRow
		if err := rows.Scan(
			&i.ProductID,
			&i.Price,
			&i.MaxQuantity,
			&i.ProductEnabled,
			&i.VariantID,
			&i.Name,
			&i.Slug,
			&i.Image,
			&i.VariantEnabled,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
