// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository_products

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/stickpro/go-store/internal/models"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) (*models.Product, error)
	CreateProductMedia(ctx context.Context, arg CreateProductMediaParams) error
	DeleteProductMedia(ctx context.Context, productID uuid.UUID) error
	DeleteSpecificRelatedProducts(ctx context.Context, arg DeleteSpecificRelatedProductsParams) error
	GetByExternalID(ctx context.Context, externalID pgtype.Text) (*models.Product, error)
	GetByID(ctx context.Context, id uuid.UUID) (*models.Product, error)
	GetBySlug(ctx context.Context, slug string) (*models.Product, error)
	GetCartItemsByVariantIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]*GetCartItemsByVariantIDsRow, error)
	GetMediaByProductID(ctx context.Context, productID uuid.UUID) ([]*models.Medium, error)
	GetRelatedProductsBySlug(ctx context.Context, slug string) ([]*GetRelatedProductsBySlugRow, error)
	GetRelatedProductsByVariantID(ctx context.Context, variantID uuid.UUID) ([]*GetRelatedProductsByVariantIDRow, error)
	GetRelatedProductsByVariantIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]*GetRelatedProductsByVariantIDsRow, error)
	SyncRelatedProducts(ctx context.Context, arg SyncRelatedProductsParams) error
	Update(ctx context.Context, arg UpdateParams) (*models.Product, error)
}

var _ Querier = (*Queries)(nil)
