// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: related_products.sql

package repository_products

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
	"github.com/stickpro/go-store/internal/constant"
)

const deleteSpecificRelatedProducts = `-- name: DeleteSpecificRelatedProducts :exec
DELETE FROM related_products
WHERE variant_id = $1
  AND related_variant_id = ANY($2::uuid[])
`

type DeleteSpecificRelatedProductsParams struct {
	VariantID uuid.UUID   `db:"variant_id" json:"variant_id"`
	Column2   []uuid.UUID `db:"column_2" json:"column_2"`
}

func (q *Queries) DeleteSpecificRelatedProducts(ctx context.Context, arg DeleteSpecificRelatedProductsParams) error {
	_, err := q.db.Exec(ctx, deleteSpecificRelatedProducts, arg.VariantID, arg.Column2)
	return err
}

const getRelatedProductsBySlug = `-- name: GetRelatedProductsBySlug :many
SELECT pv.id,
       pv.product_id,
       pv.name,
       pv.slug,
       pv.is_enable,
       pv.model,
       p.price_retail,
       p.price_business,
       p.price_wholesale,
       p.stock_status,
       img.id            AS image_id,
       img.path          AS image_path,
       img.width         AS image_width,
       img.height        AS image_height
FROM related_products rp
         JOIN product_variants pv ON rp.related_variant_id = pv.id
         JOIN products p ON pv.product_id = p.id
 LEFT JOIN LATERAL (
             SELECT pm.media_id FROM product_media pm
             WHERE pm.product_id = p.id ORDER BY pm.sort_order LIMIT 1
         ) mm ON true
         LEFT JOIN media img ON img.id = mm.media_id
WHERE rp.variant_id = (SELECT id FROM product_variants pv2 WHERE pv2.slug = $1)
  AND pv.is_enable = true
ORDER BY pv.name
`

type GetRelatedProductsBySlugRow struct {
	ID             uuid.UUID            `db:"id" json:"id"`
	ProductID      uuid.UUID            `db:"product_id" json:"product_id"`
	Name           string               `db:"name" json:"name"`
	Slug           string               `db:"slug" json:"slug"`
	IsEnable       bool                 `db:"is_enable" json:"is_enable"`
	Model          string               `db:"model" json:"model"`
	PriceRetail    decimal.Decimal      `db:"price_retail" json:"price_retail"`
	PriceBusiness  decimal.Decimal      `db:"price_business" json:"price_business"`
	PriceWholesale decimal.Decimal      `db:"price_wholesale" json:"price_wholesale"`
	StockStatus    constant.StockStatus `db:"stock_status" json:"stock_status"`
	ImageID        uuid.NullUUID        `db:"image_id" json:"image_id"`
	ImagePath      pgtype.Text          `db:"image_path" json:"image_path"`
	ImageWidth     pgtype.Int4          `db:"image_width" json:"image_width"`
	ImageHeight    pgtype.Int4          `db:"image_height" json:"image_height"`
}

func (q *Queries) GetRelatedProductsBySlug(ctx context.Context, slug string) ([]*GetRelatedProductsBySlugRow, error) {
	rows, err := q.db.Query(ctx, getRelatedProductsBySlug, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetRelatedProductsBySlugRow{}
	for rows.Next() {
		var i GetRelatedProductsBySlugRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Name,
			&i.Slug,
			&i.IsEnable,
			&i.Model,
			&i.PriceRetail,
			&i.PriceBusiness,
			&i.PriceWholesale,
			&i.StockStatus,
			&i.ImageID,
			&i.ImagePath,
			&i.ImageWidth,
			&i.ImageHeight,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRelatedProductsByVariantID = `-- name: GetRelatedProductsByVariantID :many
SELECT pv.id,
       pv.product_id,
       pv.name,
       pv.slug,
       pv.is_enable,
       pv.model,
       p.price_retail,
       p.price_business,
       p.price_wholesale,
       p.stock_status,
       img.id            AS image_id,
       img.path          AS image_path,
       img.width         AS image_width,
       img.height        AS image_height
FROM related_products rp
         JOIN product_variants pv ON rp.related_variant_id = pv.id
         JOIN products p ON pv.product_id = p.id
 LEFT JOIN LATERAL (
             SELECT pm.media_id FROM product_media pm
             WHERE pm.product_id = p.id ORDER BY pm.sort_order LIMIT 1
         ) mm ON true
         LEFT JOIN media img ON img.id = mm.media_id
WHERE rp.variant_id = $1
  AND pv.is_enable = true
ORDER BY pv.name
`

type GetRelatedProductsByVariantIDRow struct {
	ID             uuid.UUID            `db:"id" json:"id"`
	ProductID      uuid.UUID            `db:"product_id" json:"product_id"`
	Name           string               `db:"name" json:"name"`
	Slug           string               `db:"slug" json:"slug"`
	IsEnable       bool                 `db:"is_enable" json:"is_enable"`
	Model          string               `db:"model" json:"model"`
	PriceRetail    decimal.Decimal      `db:"price_retail" json:"price_retail"`
	PriceBusiness  decimal.Decimal      `db:"price_business" json:"price_business"`
	PriceWholesale decimal.Decimal      `db:"price_wholesale" json:"price_wholesale"`
	StockStatus    constant.StockStatus `db:"stock_status" json:"stock_status"`
	ImageID        uuid.NullUUID        `db:"image_id" json:"image_id"`
	ImagePath      pgtype.Text          `db:"image_path" json:"image_path"`
	ImageWidth     pgtype.Int4          `db:"image_width" json:"image_width"`
	ImageHeight    pgtype.Int4          `db:"image_height" json:"image_height"`
}

func (q *Queries) GetRelatedProductsByVariantID(ctx context.Context, variantID uuid.UUID) ([]*GetRelatedProductsByVariantIDRow, error) {
	rows, err := q.db.Query(ctx, getRelatedProductsByVariantID, variantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetRelatedProductsByVariantIDRow{}
	for rows.Next() {
		var i GetRelatedProductsByVariantIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Name,
			&i.Slug,
			&i.IsEnable,
			&i.Model,
			&i.PriceRetail,
			&i.PriceBusiness,
			&i.PriceWholesale,
			&i.StockStatus,
			&i.ImageID,
			&i.ImagePath,
			&i.ImageWidth,
			&i.ImageHeight,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRelatedProductsByVariantIDs = `-- name: GetRelatedProductsByVariantIDs :many
SELECT rp.variant_id,
       pv.id,
       pv.product_id,
       pv.name,
       pv.slug,
       pv.is_enable,
       pv.model,
       p.price_retail,
       p.price_business,
       p.price_wholesale,
       p.stock_status,
       img.id            AS image_id,
       img.path          AS image_path,
       img.width         AS image_width,
       img.height        AS image_height
FROM related_products rp
         JOIN product_variants pv ON rp.related_variant_id = pv.id
         JOIN products p ON pv.product_id = p.id
 LEFT JOIN LATERAL (
             SELECT pm.media_id FROM product_media pm
             WHERE pm.product_id = p.id ORDER BY pm.sort_order LIMIT 1
         ) mm ON true
         LEFT JOIN media img ON img.id = mm.media_id
WHERE rp.variant_id = ANY($1::uuid[])
  AND pv.is_enable = true
ORDER BY rp.variant_id, pv.name
`

type GetRelatedProductsByVariantIDsRow struct {
	VariantID      uuid.UUID            `db:"variant_id" json:"variant_id"`
	ID             uuid.UUID            `db:"id" json:"id"`
	ProductID      uuid.UUID            `db:"product_id" json:"product_id"`
	Name           string               `db:"name" json:"name"`
	Slug           string               `db:"slug" json:"slug"`
	IsEnable       bool                 `db:"is_enable" json:"is_enable"`
	Model          string               `db:"model" json:"model"`
	PriceRetail    decimal.Decimal      `db:"price_retail" json:"price_retail"`
	PriceBusiness  decimal.Decimal      `db:"price_business" json:"price_business"`
	PriceWholesale decimal.Decimal      `db:"price_wholesale" json:"price_wholesale"`
	StockStatus    constant.StockStatus `db:"stock_status" json:"stock_status"`
	ImageID        uuid.NullUUID        `db:"image_id" json:"image_id"`
	ImagePath      pgtype.Text          `db:"image_path" json:"image_path"`
	ImageWidth     pgtype.Int4          `db:"image_width" json:"image_width"`
	ImageHeight    pgtype.Int4          `db:"image_height" json:"image_height"`
}

func (q *Queries) GetRelatedProductsByVariantIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]*GetRelatedProductsByVariantIDsRow, error) {
	rows, err := q.db.Query(ctx, getRelatedProductsByVariantIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetRelatedProductsByVariantIDsRow{}
	for rows.Next() {
		var i GetRelatedProductsByVariantIDsRow
		if err := rows.Scan(
			&i.VariantID,
			&i.ID,
			&i.ProductID,
			&i.Name,
			&i.Slug,
			&i.IsEnable,
			&i.Model,
			&i.PriceRetail,
			&i.PriceBusiness,
			&i.PriceWholesale,
			&i.StockStatus,
			&i.ImageID,
			&i.ImagePath,
			&i.ImageWidth,
			&i.ImageHeight,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const syncRelatedProducts = `-- name: SyncRelatedProducts :exec
WITH deleted AS (
    DELETE FROM related_products
    WHERE variant_id = $1::uuid
)
INSERT INTO related_products (variant_id, related_variant_id)
SELECT $1::uuid, v.id
FROM product_variants v
WHERE v.id = ANY($2::uuid[])
  AND v.id != $1::uuid
ON CONFLICT DO NOTHING
`

type SyncRelatedProductsParams struct {
	VariantID         uuid.UUID   `db:"variant_id" json:"variant_id"`
	RelatedVariantIds []uuid.UUID `db:"related_variant_ids" json:"related_variant_ids"`
}

func (q *Queries) SyncRelatedProducts(ctx context.Context, arg SyncRelatedProductsParams) error {
	_, err := q.db.Exec(ctx, syncRelatedProducts, arg.VariantID, arg.RelatedVariantIds)
	return err
}
