// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository_category_paths

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	DeleteCategoryPaths(ctx context.Context, ancestorID uuid.UUID) error
	GetAllAncestors(ctx context.Context, descendantID uuid.UUID) ([]*GetAllAncestorsRow, error)
	GetAllDescendants(ctx context.Context, ancestorID uuid.UUID) ([]*GetAllDescendantsRow, error)
	GetBreadcrumbsByCategoryID(ctx context.Context, descendantID uuid.UUID) ([]*GetBreadcrumbsByCategoryIDRow, error)
	GetBreadcrumbsByCategorySlug(ctx context.Context, slug string) ([]*GetBreadcrumbsByCategorySlugRow, error)
	GetBreadcrumbsByProductSlug(ctx context.Context, slug string) ([]*GetBreadcrumbsByProductSlugRow, error)
	GetCategoryDepth(ctx context.Context, descendantID uuid.UUID) (interface{}, error)
	GetCategoryPathsBatch(ctx context.Context, dollar_1 []uuid.UUID) ([]*GetCategoryPathsBatchRow, error)
	GetDirectChildren(ctx context.Context, ancestorID uuid.UUID) ([]*GetDirectChildrenRow, error)
	InsertCategoryPath(ctx context.Context, arg InsertCategoryPathParams) error
	IsCategoryDescendantOf(ctx context.Context, arg IsCategoryDescendantOfParams) (bool, error)
}

var _ Querier = (*Queries)(nil)
