// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product_reviews.sql

package repository_product_reviews

import (
	"context"

	"github.com/google/uuid"
	"github.com/stickpro/go-store/internal/models"
)

const getByID = `-- name: GetByID :one
SELECT id, product_id, user_id, order_id, rating, title, body, status, created_at, updated_at, deleted_at FROM product_reviews
WHERE id=$1 LIMIT 1
`

func (q *Queries) GetByID(ctx context.Context, id uuid.UUID) (*models.ProductReview, error) {
	row := q.db.QueryRow(ctx, getByID, id)
	var i models.ProductReview
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.UserID,
		&i.OrderID,
		&i.Rating,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const restore = `-- name: Restore :one
UPDATE product_reviews
SET deleted_at= null, updated_at=now()
WHERE id=$1
RETURNING id, product_id, user_id, order_id, rating, title, body, status, created_at, updated_at, deleted_at
`

func (q *Queries) Restore(ctx context.Context, id uuid.UUID) (*models.ProductReview, error) {
	row := q.db.QueryRow(ctx, restore, id)
	var i models.ProductReview
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.UserID,
		&i.OrderID,
		&i.Rating,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const softDelete = `-- name: SoftDelete :exec
UPDATE product_reviews
SET deleted_at= now(), updated_at=now()
WHERE id=$1
`

func (q *Queries) SoftDelete(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDelete, id)
	return err
}

const updateStatus = `-- name: UpdateStatus :exec
UPDATE product_reviews
	SET  status=$1, updated_at=now()
	WHERE id=$2
`

type UpdateStatusParams struct {
	Status string    `db:"status" json:"status"`
	ID     uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) UpdateStatus(ctx context.Context, arg UpdateStatusParams) error {
	_, err := q.db.Exec(ctx, updateStatus, arg.Status, arg.ID)
	return err
}
