// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product_reviews_gen.sql

package repository_product_reviews

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/stickpro/go-store/internal/models"
)

const create = `-- name: Create :one
INSERT INTO product_reviews (product_id, user_id, order_id, rating, title, body, status, created_at, deleted_at)
	VALUES ($1, $2, $3, $4, $5, $6, $7, now(), $8)
	RETURNING id, product_id, user_id, order_id, rating, title, body, status, created_at, updated_at, deleted_at
`

type CreateParams struct {
	ProductID uuid.UUID        `db:"product_id" json:"product_id"`
	UserID    uuid.UUID        `db:"user_id" json:"user_id"`
	OrderID   uuid.NullUUID    `db:"order_id" json:"order_id"`
	Rating    int16            `db:"rating" json:"rating"`
	Title     pgtype.Text      `db:"title" json:"title"`
	Body      pgtype.Text      `db:"body" json:"body"`
	Status    string           `db:"status" json:"status"`
	DeletedAt pgtype.Timestamp `db:"deleted_at" json:"deleted_at"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (*models.ProductReview, error) {
	row := q.db.QueryRow(ctx, create,
		arg.ProductID,
		arg.UserID,
		arg.OrderID,
		arg.Rating,
		arg.Title,
		arg.Body,
		arg.Status,
		arg.DeletedAt,
	)
	var i models.ProductReview
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.UserID,
		&i.OrderID,
		&i.Rating,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const delete = `-- name: Delete :exec
DELETE FROM product_reviews WHERE id=$1
`

func (q *Queries) Delete(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, delete, id)
	return err
}

const update = `-- name: Update :one
UPDATE product_reviews
	SET product_id=$1, user_id=$2, order_id=$3, rating=$4, title=$5, body=$6, 
		status=$7, updated_at=now(), deleted_at=$8
	WHERE id=$9
	RETURNING id, product_id, user_id, order_id, rating, title, body, status, created_at, updated_at, deleted_at
`

type UpdateParams struct {
	ProductID uuid.UUID        `db:"product_id" json:"product_id"`
	UserID    uuid.UUID        `db:"user_id" json:"user_id"`
	OrderID   uuid.NullUUID    `db:"order_id" json:"order_id"`
	Rating    int16            `db:"rating" json:"rating"`
	Title     pgtype.Text      `db:"title" json:"title"`
	Body      pgtype.Text      `db:"body" json:"body"`
	Status    string           `db:"status" json:"status"`
	DeletedAt pgtype.Timestamp `db:"deleted_at" json:"deleted_at"`
	ID        uuid.UUID        `db:"id" json:"id"`
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) (*models.ProductReview, error) {
	row := q.db.QueryRow(ctx, update,
		arg.ProductID,
		arg.UserID,
		arg.OrderID,
		arg.Rating,
		arg.Title,
		arg.Body,
		arg.Status,
		arg.DeletedAt,
		arg.ID,
	)
	var i models.ProductReview
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.UserID,
		&i.OrderID,
		&i.Rating,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}
