// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository_product_reviews

import (
	"context"

	"github.com/google/uuid"
	"github.com/stickpro/go-store/internal/models"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) (*models.ProductReview, error)
	Delete(ctx context.Context, id uuid.UUID) error
	GetByID(ctx context.Context, id uuid.UUID) (*models.ProductReview, error)
	Restore(ctx context.Context, id uuid.UUID) (*models.ProductReview, error)
	SoftDelete(ctx context.Context, id uuid.UUID) error
	Update(ctx context.Context, arg UpdateParams) (*models.ProductReview, error)
	UpdateStatus(ctx context.Context, arg UpdateStatusParams) error
}

var _ Querier = (*Queries)(nil)
