// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository_cities

import (
	"context"

	"github.com/stickpro/go-store/internal/models"
)

type Querier interface {
	GetAll(ctx context.Context) ([]*models.City, error)
	GetByCity(ctx context.Context, city string) ([]*models.City, error)
	GetForIndex(ctx context.Context) ([]*GetForIndexRow, error)
}

var _ Querier = (*Queries)(nil)
