app:
  profile: dev
http:
  host: localhost
  port: "80"
  fetch_interval: 30s
  connect_timeout: 5s
  read_timeout: 10s
  write_timeout: 10s
  max_header_megabytes: 1
  cors:
    enabled: true
    allowed_origins: []
postgres:
  addr: ""
  db_name: ""
  user: ""
  password: ""
  conn_max_lifetime: 180
  max_open_conns: 100
  max_idle_conns: 100
  min_open_conns: 6
redis:
  addr: ""
  user: ""
  password: ""
  db_index: 0
log:
  format: json
  level: info
  console_colored: false
  trace: fatal
  with_caller: false
  with_stack_trace: false
