// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: attributes.sql

package repository_attributes

import (
	"context"

	"github.com/google/uuid"
)

const deleteByAttributeGroupID = `-- name: DeleteByAttributeGroupID :exec
DELETE FROM attributes WHERE attribute_group_id = $1::uuid
`

func (q *Queries) DeleteByAttributeGroupID(ctx context.Context, dollar_1 uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteByAttributeGroupID, dollar_1)
	return err
}
