// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attributes.sql

package repository_attributes

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/stickpro/go-store/internal/models"
)

const deleteByAttributeGroupID = `-- name: DeleteByAttributeGroupID :exec
DELETE FROM attributes WHERE attribute_group_id = $1::uuid
`

func (q *Queries) DeleteByAttributeGroupID(ctx context.Context, dollar_1 uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteByAttributeGroupID, dollar_1)
	return err
}

const getByID = `-- name: GetByID :one
SELECT id, attribute_group_id, name, slug, type, unit, is_filterable, is_visible, is_required, sort_order, created_at, updated_at FROM attributes WHERE id = $1 LIMIT 1
`

func (q *Queries) GetByID(ctx context.Context, id uuid.UUID) (*models.Attribute, error) {
	row := q.db.QueryRow(ctx, getByID, id)
	var i models.Attribute
	err := row.Scan(
		&i.ID,
		&i.AttributeGroupID,
		&i.Name,
		&i.Slug,
		&i.Type,
		&i.Unit,
		&i.IsFilterable,
		&i.IsVisible,
		&i.IsRequired,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getBySlug = `-- name: GetBySlug :one
SELECT id, attribute_group_id, name, slug, type, unit, is_filterable, is_visible, is_required, sort_order, created_at, updated_at FROM attributes WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetBySlug(ctx context.Context, slug string) (*models.Attribute, error) {
	row := q.db.QueryRow(ctx, getBySlug, slug)
	var i models.Attribute
	err := row.Scan(
		&i.ID,
		&i.AttributeGroupID,
		&i.Name,
		&i.Slug,
		&i.Type,
		&i.Unit,
		&i.IsFilterable,
		&i.IsVisible,
		&i.IsRequired,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getFilterableAttributes = `-- name: GetFilterableAttributes :many
SELECT
    a.id,
    a.attribute_group_id,
    a.name,
    a.slug,
    a.type,
    a.unit,
    a.is_filterable,
    a.is_visible,
    a.is_required,
    a.sort_order,
    a.created_at,
    a.updated_at,
    ag.name as group_name,
    ag.slug as group_slug
FROM attributes a
INNER JOIN attribute_groups ag ON a.attribute_group_id = ag.id
WHERE a.is_filterable = true
ORDER BY ag.name ASC, a.sort_order ASC, a.name ASC
`

type GetFilterableAttributesRow struct {
	ID               uuid.UUID        `db:"id" json:"id"`
	AttributeGroupID uuid.NullUUID    `db:"attribute_group_id" json:"attribute_group_id"`
	Name             string           `db:"name" json:"name"`
	Slug             string           `db:"slug" json:"slug"`
	Type             string           `db:"type" json:"type"`
	Unit             pgtype.Text      `db:"unit" json:"unit"`
	IsFilterable     pgtype.Bool      `db:"is_filterable" json:"is_filterable"`
	IsVisible        pgtype.Bool      `db:"is_visible" json:"is_visible"`
	IsRequired       pgtype.Bool      `db:"is_required" json:"is_required"`
	SortOrder        pgtype.Int4      `db:"sort_order" json:"sort_order"`
	CreatedAt        pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	GroupName        string           `db:"group_name" json:"group_name"`
	GroupSlug        string           `db:"group_slug" json:"group_slug"`
}

func (q *Queries) GetFilterableAttributes(ctx context.Context) ([]*GetFilterableAttributesRow, error) {
	rows, err := q.db.Query(ctx, getFilterableAttributes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetFilterableAttributesRow{}
	for rows.Next() {
		var i GetFilterableAttributesRow
		if err := rows.Scan(
			&i.ID,
			&i.AttributeGroupID,
			&i.Name,
			&i.Slug,
			&i.Type,
			&i.Unit,
			&i.IsFilterable,
			&i.IsVisible,
			&i.IsRequired,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GroupName,
			&i.GroupSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
