// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository_attributes

import (
	"context"

	"github.com/stickpro/go-store/internal/models"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) (*models.Attribute, error)
	GetAll(ctx context.Context, arg GetAllParams) ([]*models.Attribute, error)
	Update(ctx context.Context, arg UpdateParams) (*models.Attribute, error)
}

var _ Querier = (*Queries)(nil)
