// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository_attributes

import (
	"context"

	"github.com/google/uuid"
	"github.com/stickpro/go-store/internal/models"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) (*models.Attribute, error)
	Delete(ctx context.Context, id uuid.UUID) error
	DeleteByAttributeGroupID(ctx context.Context, dollar_1 uuid.UUID) error
	GetAll(ctx context.Context, arg GetAllParams) ([]*models.Attribute, error)
	GetAttributesProduct(ctx context.Context, dollar_1 uuid.UUID) ([]*GetAttributesProductRow, error)
	GetByID(ctx context.Context, id uuid.UUID) (*models.Attribute, error)
	Update(ctx context.Context, arg UpdateParams) (*models.Attribute, error)
}

var _ Querier = (*Queries)(nil)
