// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product_variant_categories.sql

package repository_product_variant_categories

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const add = `-- name: Add :exec
INSERT INTO product_variant_categories (
    product_variant_id,
    category_id,
    created_at
) VALUES (
    $1, $2, now()
)
ON CONFLICT (product_variant_id, category_id) DO NOTHING
`

type AddParams struct {
	ProductVariantID uuid.UUID `db:"product_variant_id" json:"product_variant_id"`
	CategoryID       uuid.UUID `db:"category_id" json:"category_id"`
}

func (q *Queries) Add(ctx context.Context, arg AddParams) error {
	_, err := q.db.Exec(ctx, add, arg.ProductVariantID, arg.CategoryID)
	return err
}

const addBatch = `-- name: AddBatch :exec
INSERT INTO product_variant_categories (product_variant_id, category_id, created_at)
SELECT $1, unnest($2::uuid[]), now()
ON CONFLICT (product_variant_id, category_id) DO NOTHING
`

type AddBatchParams struct {
	ProductVariantID uuid.UUID   `db:"product_variant_id" json:"product_variant_id"`
	CategoryIds      []uuid.UUID `db:"category_ids" json:"category_ids"`
}

func (q *Queries) AddBatch(ctx context.Context, arg AddBatchParams) error {
	_, err := q.db.Exec(ctx, addBatch, arg.ProductVariantID, arg.CategoryIds)
	return err
}

const getByVariantID = `-- name: GetByVariantID :many
SELECT
    pvc.product_variant_id,
    pvc.category_id,
    pvc.created_at,
    c.name as category_name,
    c.slug as category_slug,
    c.is_enable as category_is_enable
FROM product_variant_categories pvc
INNER JOIN categories c ON pvc.category_id = c.id
WHERE pvc.product_variant_id = $1
ORDER BY c.name ASC
`

type GetByVariantIDRow struct {
	ProductVariantID uuid.UUID        `db:"product_variant_id" json:"product_variant_id"`
	CategoryID       uuid.UUID        `db:"category_id" json:"category_id"`
	CreatedAt        pgtype.Timestamp `db:"created_at" json:"created_at"`
	CategoryName     string           `db:"category_name" json:"category_name"`
	CategorySlug     string           `db:"category_slug" json:"category_slug"`
	CategoryIsEnable bool             `db:"category_is_enable" json:"category_is_enable"`
}

func (q *Queries) GetByVariantID(ctx context.Context, productVariantID uuid.UUID) ([]*GetByVariantIDRow, error) {
	rows, err := q.db.Query(ctx, getByVariantID, productVariantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetByVariantIDRow{}
	for rows.Next() {
		var i GetByVariantIDRow
		if err := rows.Scan(
			&i.ProductVariantID,
			&i.CategoryID,
			&i.CreatedAt,
			&i.CategoryName,
			&i.CategorySlug,
			&i.CategoryIsEnable,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getByVariantIDs = `-- name: GetByVariantIDs :many
SELECT
    pvc.product_variant_id,
    pvc.category_id,
    pvc.created_at,
    c.name as category_name,
    c.slug as category_slug,
    c.is_enable as category_is_enable
FROM product_variant_categories pvc
INNER JOIN categories c ON pvc.category_id = c.id
WHERE pvc.product_variant_id = ANY($1::uuid[])
ORDER BY c.name ASC
`

type GetByVariantIDsRow struct {
	ProductVariantID uuid.UUID        `db:"product_variant_id" json:"product_variant_id"`
	CategoryID       uuid.UUID        `db:"category_id" json:"category_id"`
	CreatedAt        pgtype.Timestamp `db:"created_at" json:"created_at"`
	CategoryName     string           `db:"category_name" json:"category_name"`
	CategorySlug     string           `db:"category_slug" json:"category_slug"`
	CategoryIsEnable bool             `db:"category_is_enable" json:"category_is_enable"`
}

func (q *Queries) GetByVariantIDs(ctx context.Context, variantIds []uuid.UUID) ([]*GetByVariantIDsRow, error) {
	rows, err := q.db.Query(ctx, getByVariantIDs, variantIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetByVariantIDsRow{}
	for rows.Next() {
		var i GetByVariantIDsRow
		if err := rows.Scan(
			&i.ProductVariantID,
			&i.CategoryID,
			&i.CreatedAt,
			&i.CategoryName,
			&i.CategorySlug,
			&i.CategoryIsEnable,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const remove = `-- name: Remove :exec
DELETE FROM product_variant_categories
WHERE product_variant_id = $1 AND category_id = $2
`

type RemoveParams struct {
	ProductVariantID uuid.UUID `db:"product_variant_id" json:"product_variant_id"`
	CategoryID       uuid.UUID `db:"category_id" json:"category_id"`
}

func (q *Queries) Remove(ctx context.Context, arg RemoveParams) error {
	_, err := q.db.Exec(ctx, remove, arg.ProductVariantID, arg.CategoryID)
	return err
}

const removeAll = `-- name: RemoveAll :exec
DELETE FROM product_variant_categories
WHERE product_variant_id = $1
`

func (q *Queries) RemoveAll(ctx context.Context, productVariantID uuid.UUID) error {
	_, err := q.db.Exec(ctx, removeAll, productVariantID)
	return err
}
