// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository_product_variant_categories

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	Add(ctx context.Context, arg AddParams) error
	AddBatch(ctx context.Context, arg AddBatchParams) error
	GetByVariantID(ctx context.Context, productVariantID uuid.UUID) ([]*GetByVariantIDRow, error)
	GetByVariantIDs(ctx context.Context, variantIds []uuid.UUID) ([]*GetByVariantIDsRow, error)
	Remove(ctx context.Context, arg RemoveParams) error
	RemoveAll(ctx context.Context, productVariantID uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
