basePath: /api
definitions:
  APIError:
    properties:
      field:
        type: string
      message:
        type: string
    type: object
  APIErrors:
    properties:
      code:
        type: integer
      errors:
        items:
          $ref: '#/definitions/APIError'
        type: array
    type: object
  AuthRequest:
    properties:
      email:
        type: string
      password:
        maxLength: 32
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
  AuthResponse:
    properties:
      token:
        type: string
    type: object
  JSONResponse-AuthResponse:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/AuthResponse'
      message:
        type: string
    type: object
  JSONResponse-RegisterUserResponse:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/RegisterUserResponse'
      message:
        type: string
    type: object
  JSONResponse-github_com_stickpro_go-store_internal_delivery_http_response_category_response_CategoryResponse:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/github_com_stickpro_go-store_internal_delivery_http_response_category_response.CategoryResponse'
      message:
        type: string
    type: object
  RegisterRequest:
    properties:
      email:
        type: string
      language:
        maxLength: 2
        minLength: 2
        type: string
      location:
        type: string
      password:
        maxLength: 32
        minLength: 8
        type: string
    required:
    - email
    - language
    - location
    - password
    type: object
  RegisterUserResponse:
    properties:
      token:
        type: string
    type: object
  github_com_stickpro_go-store_internal_delivery_http_response_category_response.CategoryResponse:
    properties:
      created_at:
        type: string
      description:
        type: string
      id:
        type: string
      is_enabled:
        type: boolean
      meta_description:
        type: string
      meta_h1:
        type: string
      meta_keywords:
        type: string
      meta_title:
        type: string
      name:
        type: string
      slug:
        type: string
      updated_at:
        type: string
    type: object
info:
  contact:
    email: go-store@stick.sh
    name: Vladislav B
  description: This is an API for go-store
  title: GO-store
  version: "1.0"
paths:
  /v1/auth/login:
    post:
      consumes:
      - application/json
      description: Auth a user
      parameters:
      - description: Register account
        in: body
        name: register
        required: true
        schema:
          $ref: '#/definitions/AuthRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/JSONResponse-AuthResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/APIErrors'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/APIErrors'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/APIErrors'
      summary: Auth user
      tags:
      - Auth
  /v1/auth/register:
    post:
      consumes:
      - application/json
      description: Register a new user
      parameters:
      - description: Register account
        in: body
        name: register
        required: true
        schema:
          $ref: '#/definitions/RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/JSONResponse-RegisterUserResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/APIErrors'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/APIErrors'
      summary: Register user
      tags:
      - Auth
  /v1/category/:id/:
    get:
      consumes:
      - application/json
      description: Get category by id
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/JSONResponse-github_com_stickpro_go-store_internal_delivery_http_response_category_response_CategoryResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/APIErrors'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/APIErrors'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/APIErrors'
      summary: Category
      tags:
      - Auth
  /v1/category/:slug/:
    get:
      consumes:
      - application/json
      description: Get category by slug
      parameters:
      - description: Category Slug
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/JSONResponse-github_com_stickpro_go-store_internal_delivery_http_response_category_response_CategoryResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/APIErrors'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/APIErrors'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/APIErrors'
      summary: Category
      tags:
      - Auth
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
