// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository_product_attribute_values

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	Add(ctx context.Context, arg AddParams) error
	AddBatch(ctx context.Context, arg AddBatchParams) error
	GetByProductID(ctx context.Context, productID uuid.UUID) ([]*GetByProductIDRow, error)
	GetFiltersForCategory(ctx context.Context, categoryID uuid.NullUUID) ([]*GetFiltersForCategoryRow, error)
	Remove(ctx context.Context, arg RemoveParams) error
	RemoveAll(ctx context.Context, productID uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
