// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: manufacturers_gen.sql

package repository_manufacturers

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/stickpro/go-store/internal/models"
)

const create = `-- name: Create :one
INSERT INTO manufacturers (name, slug, description, image_path, meta_title, meta_h1, meta_description, meta_keyword, is_enable, created_at)
	VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, now())
	RETURNING id, name, slug, description, image_path, meta_title, meta_h1, meta_description, meta_keyword, is_enable, created_at, updated_at
`

type CreateParams struct {
	Name            string      `db:"name" json:"name"`
	Slug            string      `db:"slug" json:"slug"`
	Description     pgtype.Text `db:"description" json:"description"`
	ImagePath       pgtype.Text `db:"image_path" json:"image_path"`
	MetaTitle       pgtype.Text `db:"meta_title" json:"meta_title"`
	MetaH1          pgtype.Text `db:"meta_h1" json:"meta_h1"`
	MetaDescription pgtype.Text `db:"meta_description" json:"meta_description"`
	MetaKeyword     pgtype.Text `db:"meta_keyword" json:"meta_keyword"`
	IsEnable        bool        `db:"is_enable" json:"is_enable"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (*models.Manufacturer, error) {
	row := q.db.QueryRow(ctx, create,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.ImagePath,
		arg.MetaTitle,
		arg.MetaH1,
		arg.MetaDescription,
		arg.MetaKeyword,
		arg.IsEnable,
	)
	var i models.Manufacturer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.ImagePath,
		&i.MetaTitle,
		&i.MetaH1,
		&i.MetaDescription,
		&i.MetaKeyword,
		&i.IsEnable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const update = `-- name: Update :one
UPDATE manufacturers
	SET name=$1, slug=$2, description=$3, image_path=$4, meta_title=$5, meta_h1=$6, 
		meta_description=$7, meta_keyword=$8, is_enable=$9, updated_at=now()
	WHERE id=$10
	RETURNING id, name, slug, description, image_path, meta_title, meta_h1, meta_description, meta_keyword, is_enable, created_at, updated_at
`

type UpdateParams struct {
	Name            string      `db:"name" json:"name"`
	Slug            string      `db:"slug" json:"slug"`
	Description     pgtype.Text `db:"description" json:"description"`
	ImagePath       pgtype.Text `db:"image_path" json:"image_path"`
	MetaTitle       pgtype.Text `db:"meta_title" json:"meta_title"`
	MetaH1          pgtype.Text `db:"meta_h1" json:"meta_h1"`
	MetaDescription pgtype.Text `db:"meta_description" json:"meta_description"`
	MetaKeyword     pgtype.Text `db:"meta_keyword" json:"meta_keyword"`
	IsEnable        bool        `db:"is_enable" json:"is_enable"`
	ID              uuid.UUID   `db:"id" json:"id"`
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) (*models.Manufacturer, error) {
	row := q.db.QueryRow(ctx, update,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.ImagePath,
		arg.MetaTitle,
		arg.MetaH1,
		arg.MetaDescription,
		arg.MetaKeyword,
		arg.IsEnable,
		arg.ID,
	)
	var i models.Manufacturer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.ImagePath,
		&i.MetaTitle,
		&i.MetaH1,
		&i.MetaDescription,
		&i.MetaKeyword,
		&i.IsEnable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
