// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: manufacturers.sql

package repository_manufacturers

import (
	"context"

	"github.com/google/uuid"
	"github.com/stickpro/go-store/internal/models"
)

const getByID = `-- name: GetByID :one
SELECT id, name, slug, description, image_path, meta_title, meta_h1, meta_description, meta_keyword, is_enable, created_at, updated_at FROM manufacturers WHERE id = $1 LIMIT 1
`

func (q *Queries) GetByID(ctx context.Context, id uuid.UUID) (*models.Manufacturer, error) {
	row := q.db.QueryRow(ctx, getByID, id)
	var i models.Manufacturer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.ImagePath,
		&i.MetaTitle,
		&i.MetaH1,
		&i.MetaDescription,
		&i.MetaKeyword,
		&i.IsEnable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getByIDs = `-- name: GetByIDs :many
SELECT id, name, slug, description, image_path, meta_title, meta_h1, meta_description, meta_keyword, is_enable, created_at, updated_at FROM manufacturers WHERE id = ANY($1::uuid[])
`

func (q *Queries) GetByIDs(ctx context.Context, ids []uuid.UUID) ([]*models.Manufacturer, error) {
	rows, err := q.db.Query(ctx, getByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*models.Manufacturer{}
	for rows.Next() {
		var i models.Manufacturer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.ImagePath,
			&i.MetaTitle,
			&i.MetaH1,
			&i.MetaDescription,
			&i.MetaKeyword,
			&i.IsEnable,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBySlug = `-- name: GetBySlug :one
SELECT id, name, slug, description, image_path, meta_title, meta_h1, meta_description, meta_keyword, is_enable, created_at, updated_at FROM manufacturers WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetBySlug(ctx context.Context, slug string) (*models.Manufacturer, error) {
	row := q.db.QueryRow(ctx, getBySlug, slug)
	var i models.Manufacturer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.ImagePath,
		&i.MetaTitle,
		&i.MetaH1,
		&i.MetaDescription,
		&i.MetaKeyword,
		&i.IsEnable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
