// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository_manufacturers

import (
	"context"

	"github.com/google/uuid"
	"github.com/stickpro/go-store/internal/models"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) (*models.Manufacturer, error)
	GetByID(ctx context.Context, id uuid.UUID) (*models.Manufacturer, error)
	GetBySlug(ctx context.Context, slug string) (*models.Manufacturer, error)
	Update(ctx context.Context, arg UpdateParams) (*models.Manufacturer, error)
}

var _ Querier = (*Queries)(nil)
